--------------------------------------------------------
--  DDL for Table XXDM_SALES_BOOKINGS
--------------------------------------------------------

  CREATE TABLE "XXDM_SALES_BOOKINGS" 
   (	"BUSINESS_UNIT" VARCHAR2(250), 
	"BOOKING_NUMBER" VARCHAR2(250), 
	"BOOKING_DATE" DATE, 
	"PAYMENT_PLAN" VARCHAR2(250), 
	"PRICELIST" VARCHAR2(250), 
	"BOOKING_TYPE" VARCHAR2(250), 
	"CURRENCY" VARCHAR2(250), 
	"BOOKING_FLAG" VARCHAR2(250), 
	"STATUS" VARCHAR2(250), 
	"DESCRIPTION" VARCHAR2(250), 
	"CUSTOMER" VARCHAR2(250), 
	"CUSTOMER_BILL_TO" VARCHAR2(250), 
	"PROPERTY" VARCHAR2(250), 
	"BUILDING" VARCHAR2(250), 
	"UNIT" VARCHAR2(250), 
	"UOM" VARCHAR2(250), 
	"BOOKING_AMOUNT" VARCHAR2(250), 
	"DISCOUNT_PERCENTAGE" VARCHAR2(250), 
	"DISCOUNT_AMOUNT" VARCHAR2(250), 
	"TAX_CODE" VARCHAR2(250), 
	"TAX_RATE" VARCHAR2(250), 
	"TAX_AMOUNT" VARCHAR2(250), 
	"STATUS_FLAG" VARCHAR2(5), 
	"ERR_DESC" VARCHAR2(250), 
	"ORG_ID" NUMBER, 
	"CUST_ID" NUMBER, 
	"BILL_TO_SITE_ID" NUMBER, 
	"PROPERTY_ID" NUMBER, 
	"BUILDING_ID" NUMBER, 
	"UNIT_ID" NUMBER, 
	"BOOKING_RATE" VARCHAR2(250), 
	"MS_HDR_ID" NUMBER, 
	"PL_ID" NUMBER
   )
