--------------------------------------------------------
--  DDL for View XXPM_BILLING_BOOKING_V
--------------------------------------------------------

  CREATE OR REPLACE VIEW "XXPM_BILLING_BOOKING_V" ("INSTALLMENT_EVENT", "STATUS", "BOOKING_MS_DTL_ID", "BILLING_ID", "MILESTONE_TYPE", "INSTALLMENT_TYPE", "INSTALLMENT_DISP_NAME", "CHARGE_TYPE", "DUE_DATE", "INSTALLMENT_AMOUNT", "RATE", "BOOKING_HDR_ID", "BOOKING_NUMBER", "PROPERTY_ID", "ORG_ID", "CUST_BOOKING_HDR_ID", "CUST_ID", "CUSTOMER_NAME", "ORG_NAME", "PROPERTY_NAME", "OFFER_HDR_ID", "OFFER_NUMBER", "UNIT_NUMBER", "UNIT_NAME", "USAGE") AS select distinct
  XBM.INSTALLMENT_EVENT,
  XBH.STATUS,
XBM.BOOKING_MS_DTL_ID,
XBM.BILLING_ID,
XBM.MILESTONE_TYPE,
XBM.INSTALLMENT_TYPE,
--LK.LOOKUP_VALUE_NAME_DISP,
(SELECT LOOKUP_VALUE_NAME_DISP FROM XXFND_LOOKUP_V XV WHERE XV.LOOKUP_TYPE_NAME = 'MILESTONE_INSTALLMENT' AND XV.LOOKUP_VALUE_NAME = XBM.INSTALLMENT_TYPE) AS LOOKUP_VALUE_NAME_DISP,
XBM.CHARGE_TYPE,
XBM.DUE_DATE,
XBM.INSTALLMENT_AMOUNT,
XBM.RATE,
XBH.BOOKING_HDR_ID,
XBH.BOOKING_NUMBER,
XBH.PROPERTY_ID,
XBH.ORG_ID,
XBC.BOOKING_HDR_ID,
XBC.CUST_ID,
XSC.CUSTOMER_NAME,
XSO.ORG_NAME,
XPM.PROPERTY_NAME,
XBH.OFFER_HDR_ID,
XOH.OFFER_NUMBER,
(select XPU.UNIT_NUMBER from  XXPM_PROPERTY_UNITS XPU where XPU.UNIT_ID=XBD.UNIT_ID) UNIT_NUMBER,
(select XPU.UNIT_NAME from  XXPM_PROPERTY_UNITS XPU where XPU.UNIT_ID=XBD.UNIT_ID) UNIT_NAME,
XBH.USAGE
from XXPM_BOOKING_MILESTONES XBM,XXPM_BOOKING_HEADER XBH,
XXPM_BOOKING_DETAIL XBD,
XXPM_BOOKING_CUSTOMER XBC,
XXSTG_CUSTOMER XSC,XXSTG_ORGANIZATIONS XSO
--, XXFND_LOOKUP_V LK
,XXPM_PROPERTY_MASTER XPM, XXPM_OFFER_HEADER XOH
where BILLING_ID is null
and XBM.BOOKING_HDR_ID=XBH.BOOKING_HDR_ID (+)
and XBM.BOOKING_HDR_ID=XBC.BOOKING_HDR_ID (+)
and XBC.CUST_ID=XSC.CUST_ID (+)
and XBH.ORG_ID=XSO.ORG_ID(+)
AND XBC.PRIMARY_YN = 'Y'
--and XBM.INSTALLMENT_TYPE=LK.LOOKUP_VALUE_NAME(+)
and XBH.PROPERTY_ID=XPM.PROPERTY_ID (+)
and XBH.OFFER_HDR_ID=XOH.OFFER_HDR_ID(+)
and XBH.BOOKING_HDR_ID=XBD.BOOKING_HDR_ID(+)
AND   NVL(XBM.INCLUDED_IN_RATE,'N') ='N' 
AND (XBM.WAVE_OFF IS NULL OR XBM.WAVE_OFF NOT IN ('Y'))
order by XBM.BOOKING_MS_DTL_ID
