--------------------------------------------------------
--  DDL for Type PL_QUALIFIERS_OBJ_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "PL_QUALIFIERS_OBJ_TYPE" force AS OBJECT (	
PL_QLFY_ID	NUMBER,
PL_MOD_ID	NUMBER,
QLFY_ID	NUMBER,
START_DATE	VARCHAR2(200),
END_DATE	VARCHAR2(200),
ACTIVE_YN	VARCHAR2(1),
PL_MOD_NUMBER VARCHAR2(50),
CONSTRUCTOR FUNCTION PL_QUALIFIERS_OBJ_TYPE RETURN SELF AS RESULT);
