--------------------------------------------------------
--  DDL for Table XXDM_SALES_MILESTONES
--------------------------------------------------------

  CREATE TABLE "XXDM_SALES_MILESTONES" 
   (	"BOOKING_NUMBER" VARCHAR2(250), 
	"MILESTONE_TYPE" VARCHAR2(250), 
	"INSTALLMENT_TYPE" VARCHAR2(250), 
	"INSTALLMENT_PERCENATGE" VARCHAR2(250), 
	"INSTALLMENT_AMOUNT" VARCHAR2(250), 
	"UOM" VARCHAR2(250), 
	"QUANTITY" VARCHAR2(250), 
	"RATE" VARCHAR2(250), 
	"CHARGE_TYPE" VARCHAR2(250), 
	"PAYMENT_TERM" VARCHAR2(250), 
	"REMARKS" VARCHAR2(250), 
	"DUE_DAYS" VARCHAR2(250), 
	"DUE_DAYS_FROM" DATE, 
	"DUE_DATE" DATE, 
	"INVOICE_NUMBER" VARCHAR2(250), 
	"STATUS_FLAG" VARCHAR2(5), 
	"ERR_DESC" VARCHAR2(250), 
	"MILESTONE_TYPE_NAME" VARCHAR2(250), 
	"INSTALLMENT_TYPE_NAME" VARCHAR2(250), 
	"CHARGE_TYPE_NAME" VARCHAR2(250), 
	"PAYMENT_TERM_NAME" VARCHAR2(250), 
	"OFFER_HDR_ID" NUMBER
   )
