--------------------------------------------------------
--  DDL for Table XXPM_REVISION
--------------------------------------------------------

  CREATE TABLE "XXPM_REVISION" 
   (	"PL_REVISON_ID" NUMBER, 
	"PL_ID" NUMBER, 
	"REVISON_NO" VARCHAR2(60), 
	"REVISION_TYPE" VARCHAR2(3), 
	"REVISION_VALUE" NUMBER, 
	"DESCRIPTION" VARCHAR2(2000), 
	"REVISED_DATE" DATE, 
	"REVISED_BY" VARCHAR2(150), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"START_DATE" DATE, 
	"END_DATE" DATE
   )
