--------------------------------------------------------
--  DDL for Table XXSF_AGENCY
--------------------------------------------------------

  CREATE TABLE "XXSF_AGENCY" 
   (	"AGENCY_NAME" VARCHAR2(240), 
	"AGENCY_ID" VARCHAR2(240), 
	"SALE_MANAGER" VARCHAR2(240), 
	"MOBILE" VARCHAR2(240), 
	"EMAIL" VARCHAR2(240), 
	"WEBSITE" VARCHAR2(240), 
	"AGENCY_TYPE" VARCHAR2(240), 
	"CONTRACT_TYPE" VARCHAR2(240), 
	"CURRENT_OWNER" VARCHAR2(240), 
	"RECORD_TYPE" VARCHAR2(240), 
	"STATUS" VARCHAR2(240), 
	"AGREEMENT_START_DATE" DATE, 
	"AGREEMENT_END_DATE" DATE, 
	"AGREEMENT_STATUS" VARCHAR2(240), 
	"CREATION_DATE" DATE
   )
