--------------------------------------------------------
--  DDL for Type MILESTONE_LINE_OBJ_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "MILESTONE_LINE_OBJ_TYPE" force AS OBJECT (	
MS_DTL_ID	NUMBER,
MS_HDR_ID       NUMBER,
MILESTONE_NUMBER	VARCHAR2(60 BYTE),
SEQ_NUMBER	NUMBER,
INSTALLMENT_TYPE VARCHAR2(60 BYTE),
INSTALLMENT_PCT	NUMBER,
CHARGE_TYPE	VARCHAR2(60 BYTE),
PAYMENT_TERM	NUMBER,
REMARKS	VARCHAR2(4000 BYTE),
DUE_DAYS	NUMBER,
DUE_DAYS_FROM	VARCHAR2(60 BYTE),
PROJ_MS_ID	NUMBER,
DUE_DATE	VARCHAR2(11 BYTE),
REVISION	NUMBER,
REVISION_DATE	DATE,
REVISED_BY	VARCHAR2(60 BYTE),
INSTALLMENT_METHOD	VARCHAR2(30 BYTE),
INSTALLMENT_EVENT	VARCHAR2(240 BYTE),
PERIOD_OCCURENCE	VARCHAR2(30 BYTE),
PERIOD_VALUES	NUMBER,
PERIOD_DURATION	VARCHAR2(30 BYTE),
CONSTRUCTOR FUNCTION MILESTONE_LINE_OBJ_TYPE RETURN SELF AS RESULT);
