CREATE OR REPLACE PACKAGE "XXPM_ACTIVITY_PKG_TEST" is
PROCEDURE XXPM_PROC_ACTIVITY(
    SOURCE_FUNC_ID     IN NUMBER,
    SOURCE_FUNC_REF_ID IN NUMBER,
    ORG_ID             IN NUMBER,
    BOOKING_ID         IN number,
    ACTIVITY_TYPE      IN VARCHAR2,
    DESCRIPTION        IN VARCHAR2,
	CREATED_BY		   IN VARCHAR2
	);
end XXPM_ACTIVITY_PKG_TEST;
/


CREATE OR REPLACE PACKAGE BODY "XXPM_ACTIVITY_PKG_TEST" is

PROCEDURE XXPM_PROC_ACTIVITY(
    SOURCE_FUNC_ID     IN NUMBER,
    SOURCE_FUNC_REF_ID IN NUMBER,
    ORG_ID             IN NUMBER,
    BOOKING_ID         IN number,
    ACTIVITY_TYPE      IN VARCHAR2,
    DESCRIPTION        IN VARCHAR2,
	CREATED_BY		   IN VARCHAR2
    )
AS

  P_PROPERTY_ID NUMBER;
  P_BUILD_ID NUMBER;
  P_UNIT_ID NUMBER;


BEGIN


  SELECT PROPERTY_ID INTO P_PROPERTY_ID FROM XXPM_BOOKING_DETAIL WHERE BOOKING_HDR_ID = BOOKING_ID;
  SELECT BUILDING_ID INTO P_BUILD_ID FROM XXPM_BOOKING_DETAIL WHERE BOOKING_HDR_ID = BOOKING_ID;
  SELECT UNIT_ID INTO P_UNIT_ID FROM XXPM_BOOKING_DETAIL WHERE BOOKING_HDR_ID = BOOKING_ID;
    INSERT
    INTO XXPM_ACTIVITY_LOG
      (
        ACTIVITY_ID,
        ACTIVITY_NUMBER,
        ACTIVITY_DATE,
        FUNC_ID,
        SOURCE_FUNC_ID,
        SOURCE_FUNC_REF_ID,
        ORG_ID,
        PROPERTY_ID,
        BUILD_ID,
        UNIT_ID,
        ACTIVITY_TYPE,
        DESCRIPTION,
        CREATED_BY,
        CREATION_DATE,
        LAST_UPDATED_BY,
        LAST_UPDATE_DATE,
        LAST_UPDATE_LOGIN
      )
      VALUES
      (
        XXPM_ACTIVITY_ID_S.nextval,
        'AL-'|| XXPM_ACTIVITY_ID_S.nextval,
        sysdate,
        49,
        SOURCE_FUNC_ID,
        SOURCE_FUNC_REF_ID,
        ORG_ID,
        P_PROPERTY_ID,
        P_BUILD_ID,
        P_UNIT_ID,
        'BKSB',
        DESCRIPTION,
        CREATED_BY,
        SYSDATE,
        CREATED_BY,
        SYSDATE,
        CREATED_BY
      );
      
--commit;
END;
end XXPM_ACTIVITY_PKG_TEST;
/
