--------------------------------------------------------
--  DDL for Table XXFND_LOOKUP_TYPES
--------------------------------------------------------

  CREATE TABLE "XXFND_LOOKUP_TYPES" 
   (	"LOOKUP_TYPE_ID" NUMBER, 
	"LOOKUP_TYPE_NAME" VARCHAR2(30), 
	"LOOKUP_TYPE_NAME_DISP" VARCHAR2(240), 
	"LOOKUP_TYPE_NAME_DISP_TL" VARCHAR2(240), 
	"ACCESS_LEVEL" VARCHAR2(240), 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"PARENT_TYPE_ID" NUMBER
   )
