--------------------------------------------------------
--  DDL for Table XXDM_INTERFACE_MASTER
--------------------------------------------------------

  CREATE TABLE "XXDM_INTERFACE_MASTER" 
   (	"IFACE_ID" NUMBER, 
	"IFACE_NAME" VARCHAR2(100), 
	"IFACE_SHORT_NAME" VARCHAR2(30), 
	"STAGING_TABLE" VARCHAR2(60), 
	"VALIDATION_PROC" VARCHAR2(60), 
	"PROCESS_PROC" VARCHAR2(60), 
	"DATA_EXTRACTION_PROC" VARCHAR2(60), 
	"DATA_EXTRACTION_OBJ_TYPE" VARCHAR2(60), 
	"DATA_EXTRACTION_TABLE_TYPE" VARCHAR2(60), 
	"PARENT_IFACE_ID" NUMBER, 
	"LOOKUP_TYPE" VARCHAR2(1000), 
	"DEFAULT_TAB" VARCHAR2(1000), 
	"DISPLAY_ORDER" NUMBER, 
	"CREATED_BY" VARCHAR2(100), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" VARCHAR2(100)
   )
