--------------------------------------------------------
--  DDL for Table XXPM_AR_SETUP
--------------------------------------------------------

  CREATE TABLE "XXPM_AR_SETUP" 
   (	"AR_SETUP_ID" NUMBER, 
	"BUSINESS_UNIT_ID" NUMBER, 
	"LEGAL_ENTITY_ID" NUMBER, 
	"CHARGE_TYPE" VARCHAR2(50), 
	"TXN_TYPE" VARCHAR2(240), 
	"TXN_SOURCE" VARCHAR2(240), 
	"CM_TXN_TYPE" VARCHAR2(240), 
	"CM_TXN_SOURCE" VARCHAR2(240), 
	"TYPE_ID" VARCHAR2(240), 
	"TXN_TYPE_ID" NUMBER, 
	"TXN_SOURCE_ID" NUMBER, 
	"CM_TXN_TYPE_ID" NUMBER, 
	"CM_TXN_SOURCE_ID" NUMBER, 
	"REV_ACCOUNT_ID" NUMBER, 
	"CONCATENATED_SEGMENT" VARCHAR2(240), 
	"ACCOUNTING_RULE_NAME" VARCHAR2(150), 
	"INVOICING_RULE" VARCHAR2(100), 
	"INTERCOMPANY_GL_CODE" VARCHAR2(30), 
	"COST_CENTER_GL_CODE" VARCHAR2(30), 
	"USAGE" VARCHAR2(30), 
	"UNIT_CATEGORY" VARCHAR2(60), 
	"TAX_CODE" VARCHAR2(60)
   )
