--------------------------------------------------------
--  DDL for Table XXSTG_VEND_CONTACTS
--------------------------------------------------------

  CREATE TABLE "XXSTG_VEND_CONTACTS" 
   (	"VEND_CONTACT_ID" NUMBER, 
	"VEND_ID" NUMBER, 
	"VEND_SITE_ID" NUMBER, 
	"CONTACT_NAME" VARCHAR2(240), 
	"CONTACT_NAME_TL" VARCHAR2(240), 
	"DESIGNATION" VARCHAR2(60), 
	"MOBILE_NUMBER" VARCHAR2(60), 
	"PHONE_NUMBER" VARCHAR2(60), 
	"FAX_NUMBER" NUMBER, 
	"EMAIL_ID" VARCHAR2(60), 
	"PASSPORT_NUMBER" VARCHAR2(60), 
	"PASSPORT_EXP_DATE" DATE, 
	"NATIONAL_ID_NUMBER" VARCHAR2(60), 
	"NATIONAL_ID_EXP_DATE" DATE, 
	"ORIG_SYSTEM_REF" NUMBER, 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
