--------------------------------------------------------
--  DDL for Type PL_HEADER_OBJ_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "PL_HEADER_OBJ_TYPE" force AS OBJECT (	
PL_NUMBER VARCHAR2(60),
PL_NAME VARCHAR2(60),
PL_NAME_TL VARCHAR2(60),
DESCRIPTION VARCHAR2(2000),
ORG_ID NUMBER,
PL_TYPE VARCHAR2(60),
PRIORITY NUMBER,
USAGE VARCHAR2(30),
CURRENCY_CODE VARCHAR2(3),
START_DATE VARCHAR2(100),
END_DATE VARCHAR2(100),
STATUS VARCHAR2(30),
BASE_PRICE_YN VARCHAR2(1),
ACTIVE_YN VARCHAR2(1),
CONSTRUCTOR FUNCTION PL_HEADER_OBJ_TYPE RETURN SELF AS RESULT);
