--------------------------------------------------------
--  DDL for Table XXPM_AREA_CHANGE_HDR
--------------------------------------------------------

  CREATE TABLE "XXPM_AREA_CHANGE_HDR" 
   (	"AREA_CNG_HDR_ID" NUMBER, 
	"FUNC_ID" NUMBER, 
	"AREA_CNG_NUMBER" VARCHAR2(60), 
	"AREA_CNG_DATE" DATE, 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"SURVEYED_BY" VARCHAR2(60), 
	"SURVEYOR_ID" NUMBER, 
	"SURVEY_DATE" DATE, 
	"PROPERTY_ID" NUMBER, 
	"STATUS" VARCHAR2(60), 
	"DESCRIPTION" VARCHAR2(240), 
	"ORG_ID" NUMBER, 
	"USER_GRP_ID" NUMBER, 
	"FLOW_STATUS" VARCHAR2(60), 
	"FLOW_LEVEL" NUMBER, 
	"FLOW_WITH" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
