select                                          
    xbc.row_id,                                          
    xbc.booking_cust_id,                                          
    xbc.booking_hdr_id,                                          
    xbc.cust_id,                                          
    xbc.customer_number,                                          
    xbc.customer_name,                                          
    xbc.ship_to_site_id,                                          
    xbc.ship_to_site_number,                                          
    xbc.ship_to_site_name,                                          
    xbc.bill_to_site_id,                                          
    xbc.bill_to_site_number,                                          
    xbc.bill_to_site_name,                                          
    xbc.cust_contact_id,                                          
    xbc.contact_name,                                          
    xbc.primary_yn,                                          
    xbc.description,                                          
    xbc.attribute_category,                                          
    xbc.mobile_number,                                          
    xbc.email_id,                                          
    xbc.attribute1,                                          
    xbc.attribute2,                                          
    xbc.attribute3,                                          
    xbc.attribute4,                                          
    xbc.attribute5,                                          
    xbc.attribute6,                                          
    xbc.attribute7,                                          
    xbc.attribute8,                                          
    xbc.attribute9,                                          
    xbc.attribute10,                                          
    xbc.attribute11,                                          
    xbc.attribute12,                                          
    xbc.attribute13,                                          
    xbc.attribute14,                                          
    xbc.attribute15,                                          
    xbc.attribute16,                                          
    xbc.attribute17,                                          
    xbc.attribute18,                                          
    xbc.attribute19,                                          
    xbc.attribute20,                                          
    xbc.created_by,                                          
    xbc.creation_date,                                          
    xbc.last_updated_by,                                          
    xbc.last_update_date,                                          
    xbc.last_update_login,                            
    xbh.cust_id as customer_id_trans,                       
    xbh.booking_hdr_id as booking_hdr_id1,                   
    xbh.org_id as org_id,    
    xbh.Attribute3 as Attribute31   
from                                          
    xxpm_booking_customer_v xbc, xxpm_booking_header_v xbh                                     
where                                   
    xbc.booking_hdr_id = xbh.booking_hdr_id