--------------------------------------------------------
--  DDL for Table XXFND_USER
--------------------------------------------------------

  CREATE TABLE "XXFND_USER" 
   (	"USER_ID" NUMBER, 
	"USER_NAME" VARCHAR2(50), 
	"USER_PAWD" VARCHAR2(150), 
	"PWD_CHANGED_FLAG" VARCHAR2(1), 
	"USER_ROLE_ID" NUMBER, 
	"USER_NAME_DISP" VARCHAR2(150), 
	"USER_NAME_DISP_TL" VARCHAR2(150), 
	"DATA_GROUP_ID" NUMBER, 
	"DEF_DCOMB_ID" NUMBER, 
	"LOV_ACCESS_GRP_ID" NUMBER, 
	"EMP_ID" NUMBER, 
	"ACTIVE_YN" VARCHAR2(1), 
	"ORIG_SYSTEM_REF" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"USER_EMAIL_ID" VARCHAR2(300)
   )
