--------------------------------------------------------
--  DDL for Table XXPM_BOOK_MS_REV_HDR
--------------------------------------------------------

  CREATE TABLE "XXPM_BOOK_MS_REV_HDR" 
   (	"MS_REV_ID" NUMBER, 
	"BOOKING_HDR_ID" NUMBER, 
	"ORG_ID" NUMBER, 
	"FUNC_ID" NUMBER, 
	"MS_REV_NUMBER" VARCHAR2(60), 
	"MS_REV_DATE" DATE, 
	"USAGE" VARCHAR2(30), 
	"OBJECT_VERSION_NUMBER" NUMBER, 
	"STATUS" VARCHAR2(60), 
	"DESCRIPTION" VARCHAR2(240), 
	"FLOW_STATUS" VARCHAR2(60), 
	"FLOW_LEVEL" NUMBER, 
	"FLOW_WITH" NUMBER, 
	"USER_GRP_ID" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
