
SELECT * FROM XXDM_INTERFACE;--Excel File 
SELECT * FROM XXDM_PROPERTY_UNITS WHERE ERR_MSG IS NOT NULL;
SELECT * FROM XXDM_PROPERTY_AREA WHERE ERR_MSG IS NOT NULL;
SELECT * FROM XXDM_PROPERTY_CARPARKS WHERE ERR_MSG IS NOT NULL;
SELECT * FROM XXDM_PROPERTY_FEATURES;
SELECT * FROM XXDM_PROPERTY_FIX_FITTINGS;
--***************************************************
delete FROM XXDM_PROPERTY_UNITS;
delete FROM XXDM_PROPERTY_AREA;
delete FROM XXDM_PROPERTY_CARPARKS;
delete FROM XXDM_PROPERTY_FEATURES;
delete FROM XXDM_PROPERTY_FIX_FITTINGS;
--***************************************************

--delete FROM XXDM_INTERFACE;--Excel File 