--------------------------------------------------------
--  DDL for Table XXFND_FUNC_APPROVAL_HIST
--------------------------------------------------------

  CREATE TABLE "XXFND_FUNC_APPROVAL_HIST" 
   (	"APPR_HIST_ID" NUMBER, 
	"FUNC_ID" NUMBER, 
	"FUNC_REF_ID" NUMBER, 
	"SEQ_NUMBER" NUMBER, 
	"APPR_ROLE" VARCHAR2(30), 
	"APPROVER_ID" NUMBER, 
	"SUBMISSION_DATE" DATE, 
	"ACTION_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"STATUS" VARCHAR2(30), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"FLOW_LEVEL" NUMBER, 
	"USER_GRP_ID" NUMBER, 
	"CYCLE_NO" NUMBER, 
	"CYCLE_FLAG" VARCHAR2(1)
   )
