--------------------------------------------------------
--  DDL for Function GET_EMPTY_INTERFACE_ERROR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "GET_EMPTY_INTERFACE_ERROR" 
   RETURN VARCHAR2
   IS
   l_output varchar2(4000);
   Begin
   l_output :='<?xml version="1.0"?>
<PC>
 <PC_HEAD>
  <REP_TYPE>Invoice</REP_TYPE>
  <TRX_NO></TRX_NO>
  <TRX_DATE></TRX_DATE>
  <BOOKING_NUMBER></BOOKING_NUMBER>
  <UNIT_NUMBER></UNIT_NUMBER>
  <AMOUNT></AMOUNT>
  <INTERFACE_STATUS></INTERFACE_STATUS>
  <ERROR_MSG/>
  <STATUS>APR</STATUS>
  <ORG_NAME>-</ORG_NAME>
  <PROJ_NAME></PROJ_NAME>
  <CUSTOMER_NUMBER></CUSTOMER_NUMBER>
  <CUSTOMER_NAME></CUSTOMER_NAME>
 </PC_HEAD> 
 <PC_HEAD>
  <REP_TYPE>Receipt</REP_TYPE>
  <TRX_NO></TRX_NO>
  <TRX_DATE></TRX_DATE>
  <BOOKING_NUMBER/>
  <UNIT_NUMBER></UNIT_NUMBER>
  <AMOUNT/>
  <INTERFACE_STATUS></INTERFACE_STATUS>
  <ERROR_MSG/>
  <STATUS></STATUS>
  <ORG_NAME>-</ORG_NAME>
  <PROJ_NAME></PROJ_NAME>
  <CUSTOMER_NUMBER></CUSTOMER_NUMBER>
  <CUSTOMER_NAME></CUSTOMER_NAME>
 </PC_HEAD> 
 <PC_HEAD>
  <REP_TYPE>Receipt_Dtl</REP_TYPE>
  <TRX_NO></TRX_NO>
  <TRX_DATE></TRX_DATE>
  <BOOKING_NUMBER/>
  <UNIT_NUMBER></UNIT_NUMBER>
  <AMOUNT/>
  <INTERFACE_STATUS></INTERFACE_STATUS>
  <ERROR_MSG/>
  <STATUS/>
  <ORG_NAME>-</ORG_NAME>
  <PROJ_NAME></PROJ_NAME>
  <CUSTOMER_NUMBER></CUSTOMER_NUMBER>
  <CUSTOMER_NAME></CUSTOMER_NAME>
 </PC_HEAD>
</PC>';
   
   RETURN l_output;
END GET_EMPTY_INTERFACE_ERROR;
