SELECT
    records_from_date,
    last_schedule_time,
    next_schedule_time,
    frequency_min,
    schedule_id,
    schedule_name,
    program_name,
    bi_report_path,
    bi_report_name,
    db_refresh_pkg,
    application_name,
    created_by,
    creation_date,
    last_updated_by,
    last_update_date,
    last_update_login,
    run_status,
    status FROM xxfnd_schedule_t;
/
SELECT * FROM xxfnd_schedule_list_t;
/


CREATE TABLE "XXFND_SETUP_DETAIL" 
   (
    "SETUP_ID" NUMBER, 
	"USER_NAME" VARCHAR2(60 ), 
	"PASS_WORD" VARCHAR2(60 ), 
	"HOLD_DAY" NUMBER, 
	"ATTRIBUTE1" VARCHAR2(240 ), 
	"ATTRIBUTE2" VARCHAR2(240 ), 
	"ATTRIBUTE3" VARCHAR2(240 ), 
	"ATTRIBUTE4" VARCHAR2(240 ), 
	"ATTRIBUTE5" VARCHAR2(240 ), 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" DATE, 
	"ATTRIBUTE10" DATE, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"INVOICE_TXN_SOURCE_NAME" VARCHAR2(200 ), 
	"INVOICE_TXN_SOURCE_TYPE" VARCHAR2(200 ), 
	"CREDIT_TXN_SOURCE_NAME" VARCHAR2(200 ), 
	"CREDIT_TXN_SOURCE_TYPE" VARCHAR2(200 ), 
	"DEBIT_TXN_SOURCE_NAME" VARCHAR2(200 ), 
	"DEBIT_TXN_SOURCE_TYPE" VARCHAR2(200 ), 
	"FUSION_DOMAIN" VARCHAR2(240 ), 
	"FUSION_USERNAME" VARCHAR2(240 ), 
	"FUSION_PASSWORD" VARCHAR2(240 )
   );

CREATE UNIQUE INDEX "XXFND_SETUP_DETAIL_U1" ON "XXFND_SETUP_DETAIL" ("SETUP_ID") 

CREATE SEQUENCE SETUP_ID_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

/


CREATE TABLE "XXFND_SCHEDULE_T" 
   ("SCHEDULE_ID" NUMBER, 
	"SCHEDULE_NAME" VARCHAR2(240 ), 
	"FREQUENCY_MIN" NUMBER, 
	"PROGRAM_NAME" VARCHAR2(240 ), 
	"BI_REPORT_PATH" VARCHAR2(240 ), 
	"BI_REPORT_NAME" VARCHAR2(240 ), 
	"DB_REFRESH_PKG" VARCHAR2(240 ), 
	"APPLICATION_NAME" VARCHAR2(240 ), 
	"NEXT_SCHEDULE_TIME" TIMESTAMP (6), 
	"CREATED_BY" VARCHAR2(60 ), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60 ), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(60 ), 
	"RUN_STATUS" VARCHAR2(30 ), 
	"STATUS" VARCHAR2(30 ), 
	"LAST_SCHEDULE_TIME" TIMESTAMP (6), 
	"RECORDS_FROM_DATE" TIMESTAMP (6)
   );
   
CREATE UNIQUE INDEX "XXFND_SCHEDULE_T_U1" ON "XXFND_SCHEDULE_T" ("SCHEDULE_ID");

/

CREATE SEQUENCE SCHEDULE_ID_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

