--------------------------------------------------------
--  File created - Monday-October-26-2020   
--------------------------------------------------------
@C:\Users\Balaji\Documents\sale_backup\COMPANY_LOGO_PK.sql
@C:\Users\Balaji\Documents\sale_backup\PS_TXN_PK.sql
@C:\Users\Balaji\Documents\sale_backup\XXDMPL_OWNER_DTLE_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_BOOKING_CUSTOMER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_BOOKING_DETAIL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_BOOKING_HEADER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_EXCEL_STG_MAPPING_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_INTERFACE_MASTER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_INTERFACE_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_INVOICE_HEADER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_INVOICE_LINES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_MILESTONE_DTL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_MILESTONE_HDR_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_OFFER_DETAIL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_OFFER_HEADER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_OFFER_MILESTONE_DETAIL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PL_HEADER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PL_LINES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PL_MODIFIERS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PL_QUALIFIERS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_RECEIPT_DETAILS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_RECEIPT_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_ATTRIBUTES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_ATTR_COMB_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_ATTR_GROUP_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_ROLES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_USERS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_USER_GROUP_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_USER_LEVELS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_CHECKLIST_RESPONSE_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_CURRENCIES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_DATA_COMBINATION_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_DATA_GROUP_DETAIL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_DATA_GROUP_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_DATA_SECURITY_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEXS_CATEGORY_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEXS_DATA_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEXS_FIELDS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEXS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNCTIONS_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNCTIONS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_APPROVALS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_APPROVAL_HIST_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_APPR_LEVELS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_ATTACHMENT_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_CHECKLIST_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_LOOKUP_TYPES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_LOOKUP_TYPES_U2.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_LOOKUP_VALUES_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_LOOKUP_VALUES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_LOOKUP_VALUES_U2.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_MAIN_MENU_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_MENU_ACCESS_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_MENU_ACCESS_N2.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_MENU_ACCESS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_REPORT_PARAMS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SCHEDULE_LIST_T_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SCHEDULE_T_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SUB_MENU_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SUB_MENU_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_USER_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_USER_N2.sql
@C:\Users\Balaji\Documents\sale_backup\XXPL_OWNER_DTLE_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_ACTIVITY_LOG_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CHANGE_DLT_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CHANGE_HDR_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AR_SETUP_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BILLING_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCK_DETAIL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCK_HEADER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUSTOMER_H_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUSTOMER_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUSTOMER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DETAIL_H_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DETAIL_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DETAIL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_EVENTS_H_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_EVENTS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HEADER_H_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HEADER_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HEADER_REV_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HEADER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_REV_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_U2.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOK_MS_REV_DTL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOK_MS_REV_HDR_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CANCELLATION_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CANCEL_NOTIFY_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CREDIT_MEMO_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CREDIT_MEMO_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CUST_DETAIL_TYPES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_EXTEN_CANCEL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_HEADER_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_HEADER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_LINES_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_LINES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_KEY_DETAILS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_LEAD_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_LEASE_AGREEMENT_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_DTL_H_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_DTL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_HDR_H_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_HDR_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MODIFIERS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IN_OUT_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IO_CUST_VISIT_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IO_FIXTURES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IO_KEYS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IO_METERS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_DETAIL_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_DETAIL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_HEADER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_MILESTONE_DETAIL_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_MILESTONE_DETAIL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_ORG_ASSIGNMENT_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_DISCOUNTS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_HEADER_H_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_HEADER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_LINES_H_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_LINES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_MODIFIERS_H_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_MODIFIERS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_QUALIFIERS_H_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_QUALIFIERS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_AREA_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_AREA_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_BUILDINGS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_CARPARKS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_CONTACTS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_ESCROW_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_FEATURES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_FIX_FITTINGS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MASTER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MILESTONE_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MORTGAGE_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_ORG_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_UNITS_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_UNITS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_QUALIFIERS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_DETAILS_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_DETAILS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_N2.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_REGISTRATION_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_SETUP_DETAIL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNBLOCK_DETAIL_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNBLOCK_HEADER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_AR_TXN_SOURCE_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_AR_TXN_TYPE_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_BANKS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_BANK_ACCOUNTS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_CUSTOMER_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_CUSTOMER_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_CUST_CONTACTS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_CUST_SITES_N1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_CUST_SITES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_EMPLOYEE_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_GL_CODE_COMBINATION_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_LEAD_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_LEASE_AGREEMENT_HDR_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_LOCATIONS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_ORGANIZATIONS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_PAY_TERMS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_POSITIONS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_PROJECTS_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_PROJECT_MILESTONES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_RECEIPT_METHOD_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_SALESPERSON_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_VENDOR_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_VEND_SITES_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXXPM_BOOKING_MILESTONES_H_U1.sql
@C:\Users\Balaji\Documents\sale_backup\XXfnd_SETUP_DETAIL_U1.sql
