--------------------------------------------------------
--  DDL for Table XXSTG_LEASE_MS_DTL
--------------------------------------------------------

  CREATE TABLE "XXSTG_LEASE_MS_DTL" 
   (	"S_NO" NUMBER, 
	"BOOKING_MS_DTL_ID" NUMBER, 
	"BOOKING_ID" NUMBER, 
	"BOOKING_NUMBER" VARCHAR2(60), 
	"LEASE_NUMBER" VARCHAR2(60), 
	"MILESTONE_TYPE" VARCHAR2(60), 
	"MILESTONE_TYPE_CODE" VARCHAR2(60), 
	"INSTALLMENT_TYPE" VARCHAR2(60), 
	"INSTALLMENT_TYPE_CODE" VARCHAR2(60), 
	"INSTALLMENT_PCT" NUMBER, 
	"INSTALLMENT_AMOUNT" NUMBER, 
	"CHARGE_TYPE" VARCHAR2(60), 
	"CHARGE_TYPE_CODE" VARCHAR2(60), 
	"PAYMENT_TERM" VARCHAR2(60), 
	"PAYMENT_TERM_ID" VARCHAR2(60), 
	"REMARKS" VARCHAR2(4000), 
	"DUE_DATE" DATE, 
	"STATUS" VARCHAR2(30), 
	"ERROR_MSG" VARCHAR2(4000), 
	"SEQ_NUMBER" NUMBER, 
	"MS_DTL_ID" NUMBER
   )
