--------------------------------------------------------
--  DDL for Table XXDM_EXCEL_STG_MAPPING
--------------------------------------------------------

  CREATE TABLE "XXDM_EXCEL_STG_MAPPING" 
   (	"ESM_ID" NUMBER, 
	"IFACE_ID" NUMBER, 
	"STG_COLUMN_NAME" VARCHAR2(60), 
	"EXCEL_COLUMN_NUM" NUMBER, 
	"PROMPT_NAME" VARCHAR2(60), 
	"DISPLAY_IN_PAGE" VARCHAR2(1), 
	"MANDATORY" VARCHAR2(1) DEFAULT 'N', 
	"DEFAULT_VALUE" VARCHAR2(500), 
	"DATA_TYPE" VARCHAR2(60), 
	"CREATED_BY" VARCHAR2(100), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" VARCHAR2(100)
   )
