create or replace view XXPM_CREDIT_MEMO_SEARCH_V 
as 
SELECT 
BM.BOOKING_MS_DTL_ID,
BM.MILESTONE_TYPE,
LK.LOOKUP_VALUE_NAME_DISP as MILESTONE_TYPE_DISP,
ROUND(BM.INSTALLMENT_AMOUNT,2) as INSTALLMENT_AMOUNT,
BM.CHARGE_TYPE, 
LK1.LOOKUP_VALUE_NAME_DISP as CHARGE_TYPE_DISP, 
BM.REMARKS,
BM.SOURCE_FUNC_ID, 
BM.SOURCE_FUNC_REF_ID, 
BM.BILLING_ID,
BM.INVOICE_ID, 
BM.BOOKING_HDR_ID, 
BM.BASEAMOUNT, 
BM.TAX_RATE, 
BM.TAX_CODE, 
BM.TAX_AMOUNT,
BM.INSTALLMENT_PCT_R, 
BM.INSTALLMENT_AMOUNT_R,
INV.INVOICE_NUMBER, 
INV.INVOICE_DATE, 
INV.ORG_ID, 
INV.TRX_SOURCE, 
INV.TRX_TYPE, 
INV.CURRENCY_CODE,
INV.CUST_ID, 
INV.CUST_SITE_ID, 
INV.INTERFACE_STATUS, 
INV.OFFER_NUMBER, 
INV.BOOKING_NUMBER,
CAN.FORFIET_AMOUNT, 
CAN.REFUND_AMOUNT,
org.ORG_NAME, 
org.ORG_NAME_TL as project_name,
pay.TERM_NAME,
bd.PROPERTY_ID, 
bd.BUILDING_ID, 
bd.UNIT_ID,
pm.PROPERTY_NAME,
pu.UNIT_NUMBER,
pb.BUILD_NAME,
cus.CUSTOMER_NAME,
cus.CUSTOMER_NUMBER,
cussite.CITY,
null as CUST_BILL_TO,
null as CUST_SHIP_TO,
sum(NVL(AMOUNT,0))as INV_AMT,
NVL(null,0) as CREDIT_APPLIED_AMT,
(sum(NVL(AMOUNT,0))-NVL(null,0)) as BALANCE_AMT

FROM 
XXPM_BOOKING_MILESTONES Bm, XXPM_INVOICE_HEADER INV, XXFND_LOOKUP_V LK, XXFND_LOOKUP_V LK1
,XXPM_CANCELLATION CAN, xxpm_booking_header bh
,xxstg_organizations org
,xxstg_pay_terms pay
,XXPM_INVOICE_LINES INVLNS
,xxpm_booking_detail bd
, xxpm_property_units pu
, xxpm_property_buildings pb
, xxpm_property_master pm
,xxstg_customer cus
,xxstg_cust_sites cussite
where 
BM.BOOKING_HDR_ID=INV.BOOKING_ID
and BM.INVOICE_ID=INV.INVOICE_ID
and LK.LOOKUP_TYPE_NAME='MILESTONE_TYPE'
and LK.LOOKUP_VALUE_NAME=BM.MILESTONE_TYPE
and LK1.LOOKUP_TYPE_NAME='CHARGE_TYPE'
and LK1.LOOKUP_VALUE_NAME=BM.CHARGE_TYPE
and BM.BOOKING_HDR_ID=CAN.BOOKING_ID
and org.ORG_ID=bh.ORG_ID
and BM.BOOKING_HDR_ID=bh.BOOKING_HDR_ID
and INV.PAYMENT_TERMS=pay.TERM_ID
and bd.BOOKING_HDR_ID=BM.BOOKING_HDR_ID
and bd.BOOKING_HDR_ID=bh.BOOKING_HDR_ID
and INVLNS.INVOICE_ID=INV.INVOICE_ID
and pu.UNIT_ID=bd.UNIT_ID
and pu.BUILD_ID=pb.BUILD_ID
and pu.PROPERTY_ID=pm.PROPERTY_ID
and bd.PROPERTY_ID=pu.PROPERTY_ID 
and bd.BUILDING_ID=pu.BUILD_ID
and cus.CUST_ID=inv.CUST_ID
and cussite.ORG_ID=bh.ORG_ID
and cussite.CUST_ID=inv.CUST_ID
and BM.MILESTONE_TYPE in ('CNL','MS_CMC')
and BM.CHARGE_TYPE in ('CMC')
--And Bm.Booking_Hdr_Id=2484
--366
--2484
group by 
BM.BOOKING_MS_DTL_ID,
BM.MILESTONE_TYPE,
LK.LOOKUP_VALUE_NAME_DISP,
BM.INSTALLMENT_AMOUNT,
BM.CHARGE_TYPE, 
LK1.LOOKUP_VALUE_NAME_DISP, 
BM.REMARKS,
BM.SOURCE_FUNC_ID, 
BM.SOURCE_FUNC_REF_ID, 
BM.BILLING_ID,
BM.INVOICE_ID, 
BM.BOOKING_HDR_ID, 
BM.BASEAMOUNT, 
BM.TAX_RATE, 
BM.TAX_CODE, 
BM.TAX_AMOUNT,
BM.INSTALLMENT_PCT_R, 
BM.INSTALLMENT_AMOUNT_R,
INV.INVOICE_NUMBER, 
INV.INVOICE_DATE, 
INV.ORG_ID, 
INV.TRX_SOURCE, 
INV.TRX_TYPE, 
INV.CURRENCY_CODE,
INV.CUST_ID, 
INV.CUST_SITE_ID, 
INV.INTERFACE_STATUS, 
INV.OFFER_NUMBER, 
INV.BOOKING_NUMBER,
CAN.FORFIET_AMOUNT, 
CAN.REFUND_AMOUNT,
org.ORG_NAME, 
org.ORG_NAME_TL,
pay.TERM_NAME,
bd.PROPERTY_ID, 
bd.BUILDING_ID, 
bd.UNIT_ID,
pm.PROPERTY_NAME,
pu.UNIT_NUMBER,
pb.BUILD_NAME,
cus.CUSTOMER_NAME,
cus.CUSTOMER_NUMBER,
cussite.CITY;
--,null as CUST_BILL_TO,
--null as CUST_SHIP_TO;