--------------------------------------------------------
--  DDL for Table XXDM_PROPERTY_AREA
--------------------------------------------------------

  CREATE TABLE "XXDM_PROPERTY_AREA" 
   (	"PROPERTY_NUMBER" VARCHAR2(60), 
	"BUILD_NUMBER" VARCHAR2(60), 
	"UNIT_NUMBER" VARCHAR2(60), 
	"AREA" VARCHAR2(60), 
	"UOM" VARCHAR2(60), 
	"VALUE" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"BATCH_ID" NUMBER, 
	"INTERFACE_STATUS_FLAG" VARCHAR2(1), 
	"INTERFACE_ID" NUMBER, 
	"ERR_MSG" VARCHAR2(2000), 
	"ERR_DESCRIPTION" VARCHAR2(2000), 
	"VALIDATED_BY" VARCHAR2(60), 
	"VALIDATED_DATE" TIMESTAMP (6), 
	"PROCESSED_BY" VARCHAR2(60), 
	"PROCESSED_DATE" TIMESTAMP (6), 
	"PROPERTY_ID" NUMBER, 
	"BUILD_ID" NUMBER, 
	"UNIT_ID" NUMBER, 
	"AREA_ID" VARCHAR2(60), 
	"DIFF_VAL" NUMBER
   )
