--------------------------------------------------------
--  DDL for Table XXSTG_LEAD
--------------------------------------------------------

  CREATE TABLE "XXSTG_LEAD" 
   (	"LEAD_ID" NUMBER, 
	"LEAD_NUMBER" VARCHAR2(30), 
	"LEAD_NAME" VARCHAR2(240), 
	"LEAD_NAME_TL" VARCHAR2(240), 
	"MOBILE_NUMBER" VARCHAR2(60), 
	"PHONE_NUMBER" VARCHAR2(60), 
	"EMAIL_ID" VARCHAR2(60), 
	"ORIG_SYSTEM_REF" VARCHAR2(30), 
	"PROFESSIONAL" VARCHAR2(240), 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"LEAD_SOURCE_CHANNEL" VARCHAR2(240), 
	"LEAD_SOURCE_NAME" VARCHAR2(240)
   )
