--------------------------------------------------------
--  DDL for Table XXPM_TMP2_BOOKIMG_MILESTONE
--------------------------------------------------------

  CREATE TABLE "XXPM_TMP2_BOOKIMG_MILESTONE" 
   (	"BOOKING_NUMBER" VARCHAR2(60), 
	"SEQ_NUMBER" NUMBER, 
	"NEW_SEQ_NUMBER" NUMBER, 
	"INSTALLMENT_TYPE_NAME" VARCHAR2(240), 
	"INSTALLMENT_PCT" NUMBER, 
	"INSTALLMENT_AMOUNT" NUMBER, 
	"INSTALLMENT_TYPE" VARCHAR2(60), 
	"DISPLAY_ORDER" NUMBER, 
	"BOOKING_MS_DTL_ID" NUMBER, 
	"BOOKING_HDR_ID" NUMBER, 
	"INVOICE_NUMBER" VARCHAR2(60)
   )
