--------------------------------------------------------
--  DDL for Table XXPM_CANCEL_NOTIFY
--------------------------------------------------------

  CREATE TABLE "XXPM_CANCEL_NOTIFY" 
   (	"NOTIFY_ID" NUMBER, 
	"CANCEL_ID" NUMBER, 
	"NOTIFY_TYPE" VARCHAR2(60), 
	"NOTIFY_DATE" DATE, 
	"NOTIFY_BY" VARCHAR2(60), 
	"DUE_DATE" DATE, 
	"EMAIL_NOTIFY_YN" VARCHAR2(1), 
	"SMS_NOTIFY_YN" VARCHAR2(1), 
	"LETTER_NOTIFY_YN" VARCHAR2(1), 
	"NEWSPAPER_NOTIFY_YN" VARCHAR2(1), 
	"REMARKS" VARCHAR2(2000), 
	"ACKNOWLEDGED_YN" VARCHAR2(1), 
	"PAY_RECEIVED_YN" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
