--------------------------------------------------------
--  DDL for Type AREA_OBJ_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "AREA_OBJ_TYPE" force AS OBJECT (
    AREA_ID	NUMBER,
    PROPERTY_NUMBER VARCHAR2(60),
	PROPERTY_ID	NUMBER,
    BUILD_NUMBER VARCHAR2(60),
	BUILD_ID	NUMBER,
    UNIT_NUMBER VARCHAR2(60),
	UNIT_ID	NUMBER,
	AREA	VARCHAR2(60),
	UOM	VARCHAR2(60),
	VALUE	NUMBER,
	DESCRIPTION	VARCHAR2(4000),
	CONSTRUCTOR FUNCTION AREA_OBJ_TYPE RETURN SELF AS RESULT);
