--------------------------------------------------------
--  DDL for Table XXPM_RECEIPT_UPDATE
--------------------------------------------------------

  CREATE TABLE "XXPM_RECEIPT_UPDATE" 
   (	"RECEIPT_NUMBER" VARCHAR2(50), 
	"RECEIPT_DATE" VARCHAR2(50), 
	"RECEIPT_METHOD_NAME" VARCHAR2(50), 
	"CURRENCY_CODE" VARCHAR2(50), 
	"RECEIPT_AMOUNT" VARCHAR2(50), 
	"AMOUNT_APPLIED" VARCHAR2(50), 
	"COMMENTS" VARCHAR2(50), 
	"CUSTOMER_NAME" VARCHAR2(50), 
	"CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(50), 
	"BUSINESS_UNIT_NAME" VARCHAR2(50), 
	"GL_DATE" VARCHAR2(50), 
	"MATURITY_DATE" VARCHAR2(50), 
	"TRANSACTION_DATE" VARCHAR2(50), 
	"APPLICATION_DATE" VARCHAR2(50), 
	"ACCOUNTING_DATE" VARCHAR2(50), 
	"TRANSACTION_NUMBER" VARCHAR2(50), 
	"ORG_ID" VARCHAR2(50), 
	"CUST_ID" VARCHAR2(50), 
	"CUSTOMER_TRX_ID" VARCHAR2(20), 
	"RECEIPT_METHOD_ID" VARCHAR2(50)
   )
