SELECT * FROM XXPM_APPLY_CREDIT_MEMO

create table XXPM_APPLY_CREDIT_MEMO(
CREDIT_MEMO_ID			NUMBER,
BOOKING_ID				NUMBER,
ORG_ID					NUMBER,
ORG_NAME				VARCHAR2(240),
INVOICE_ID				NUMBER,
CREDIT_MEMO_TRX_NUMBER	VARCHAR2(60),
INVOICE_NUMBER			VARCHAR2(60),
APPLYDATE				DATE,
GLDATE					DATE,
INV_AMT					NUMBER,
APPLIED_RECEIPT_AMOUNT	NUMBER,
BALANCE					NUMBER
);

CREATE SEQUENCE CREDIT_MEMO_ID_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;