--------------------------------------------------------
--  DDL for Type MILESTONE_HEADER_OBJ_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "MILESTONE_HEADER_OBJ_TYPE" force AS OBJECT (	
MS_HDR_ID	VARCHAR2(20 BYTE),
MILESTONE_NAME	VARCHAR2(240 BYTE),
MILESTONE_NAME_TL	VARCHAR2(240 BYTE),
MILESTONE_NUMBER	VARCHAR2(240 BYTE),
MILESTONE_SHORTCODE	VARCHAR2(60 BYTE),
MILESTONE_DATE	VARCHAR2(11 BYTE),
ORG_ID	VARCHAR2(20 BYTE),
PROJECT_ID	VARCHAR2(20 BYTE),
USAGE	VARCHAR2(30 BYTE),
REVISION_NO	VARCHAR2(20 BYTE),
REVISION_DATE	VARCHAR2(11 BYTE),
REVISED_BY	VARCHAR2(60 BYTE),
DESCRIPTION	VARCHAR2(4000 BYTE),
START_DATE	VARCHAR2(11 BYTE),
END_DATE	VARCHAR2(11 BYTE),
ACTIVE_YN	VARCHAR2(1 BYTE),
STATUS	VARCHAR2(60 BYTE),
CONSTRUCTOR FUNCTION MILESTONE_HEADER_OBJ_TYPE RETURN SELF AS RESULT);
