--------------------------------------------------------
--  DDL for View XXPM_AREA_CHANGE_DLT_PCS_V_2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "XXPM_AREA_CHANGE_DLT_PCS_V_2" ("AREA_CNG_DLT_ID", "AREA_CNG_HDR_ID", "FUNC_ID", "USER_GRP_ID ", "FLOW_STATUS ", "FLOW_LEVEL", "FLOW_WITH", "AREA_CNG_NUMBER", "AREA_CNG_DATE", "PROPERTY_ID", "PROPERTY_NAME", "BUILD_ID", "BUILD_NAME", "UNIT_ID", "UNIT_NAME", "UNIT_CATEGORY", "UNIT_STATUS_DISP", "UOM_DISP", "UNIT_STATUS", "AREA_ID", "AREA_TYPE", "UOM", "OLD_AREA_VALUE", "NEW_AREA_VALUE", "BOOKING_HDR_ID", "BOOKING_NUMBER", "SPA_PCT", "AREA_VARIATION_PCT", "AREA_EXCEED_TOLERANCE", "OLD_BOOKING_AMOUNT", "NEW_BOOKING_AMOUNT", "ADJ_BOOKING_AMOUNT", "CUST_ACCEPTED_YN", "CUST_ACCEPTED", "STATUS", "DESCRIPTION", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATE_DATE", "LAST_UPDATE_LOGIN") AS SELECT 
  ACD.AREA_CNG_DLT_ID      ,
ACD.AREA_CNG_HDR_ID      ,
ACH.AREA_CNG_NUMBER,
ACH.FUNC_ID ,
ACD.USER_GRP_ID ,
ACD.FLOW_STATUS ,
ACD.FLOW_LEVEL ,
ACD.FLOW_WITH   ,
ACH.AREA_CNG_DATE,
ACD.PROPERTY_ID          ,
XPM.PROPERTY_NAME        ,
ACD.BUILD_ID             ,
XPB.BUILD_NAME           ,
ACD.UNIT_ID              ,
XPU.UNIT_NAME            ,
(select lookup_value_name_disp from XXFND_LOOKUP_V where lookup_value_name=XPU.UNIT_CATEGORY and rownum=1) as UNIT_CATEGORY,
(select lookup_value_name_disp from XXFND_LOOKUP_V where lookup_value_name=ACD.UNIT_STATUS and rownum=1) as UNIT_STATUS_DISP,
(select lookup_value_name_disp from XXFND_LOOKUP_V where lookup_value_name=ACD.UOM and rownum=1) as UOM_DISP,
ACD.UNIT_STATUS          ,
ACD.AREA_ID              ,
ACD.AREA_TYPE            ,
ACD.UOM                  ,
ACD.OLD_AREA_VALUE       ,
ACD.NEW_AREA_VALUE       ,
ACD.BOOKING_HDR_ID       ,
(select BOOKING_NUMBER FROM XXPM_BOOKING_HEADER where BOOKING_HDR_ID=ACD.BOOKING_HDR_ID and rownum=1) as BOOKING_NUMBER,
ACD.SPA_PCT              ,
ACD.AREA_VARIATION_PCT   ,
ACD.AREA_EXCEED_TOLERANCE,
ACD.OLD_BOOKING_AMOUNT   ,
ACD.NEW_BOOKING_AMOUNT   ,
ACD.ADJ_BOOKING_AMOUNT   ,
ACD.CUST_ACCEPTED_YN     ,
 CASE WHEN ACD.CUST_ACCEPTED_YN = 'Y' THEN 'Yes' WHEN ACD.CUST_ACCEPTED_YN = 'N' THEN 'No' ELSE null  END AS CUST_ACCEPTED,
ACD.STATUS               ,
ACD.DESCRIPTION          ,
ACD.CREATED_BY           ,
trunc(ACD.CREATION_DATE) as    CREATION_DATE     ,
ACD.LAST_UPDATED_BY      ,
trunc(ACD.LAST_UPDATE_DATE) as  LAST_UPDATE_DATE   ,
ACD.LAST_UPDATE_LOGIN    
FROM xxpm_property_master XPM, 
xxpm_property_buildings XPB , 
XXPM_PROPERTY_UNITS XPU ,
XXPM_AREA_CHANGE_DLT ACD,
XXPM_AREA_CHANGE_HDR ACH
WHERE 
ACH.AREA_CNG_HDR_ID=ACD.AREA_CNG_HDR_ID and
XPM.PROPERTY_ID =XPB.PROPERTY_ID
AND XPB.BUILd_ID = XPU.BUILD_ID
AND ACD.PROPERTY_ID =XPM.PROPERTY_ID
AND  ACD.BUILD_ID =XPB.BUILd_ID
AND  ACD.UNIT_ID =XPU.UNIT_ID
