--------------------------------------------------------
--  File created - Monday-August-12-2019   
--------------------------------------------------------
@C:\Users\DineshkumarP\Desktop\PROD\AREA_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\AREA_TYPE_TABLE.sql
@C:\Users\DineshkumarP\Desktop\PROD\CAR_PAK_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\CAR_PARK_TYPE_TABLE.sql
@C:\Users\DineshkumarP\Desktop\PROD\FEATURES_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\FEATURES_TABLE_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\MILESTONE_HEADER_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\MILESTONE_HEADER_TABLE_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\MILESTONE_LINE_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\MILESTONE_LINE_TABLE_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\OWNER_DTLE_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\OWNER_DTLE_TAB_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\PL_HEADER_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\PL_HEADER_TABLE_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\PL_LINE_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\PL_LINE_TABLE_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\PL_MODIFIERS_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\PL_MODIFIERS_TABLE_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\PL_QUALIFIERS_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\PL_QUALIFIERS_TABLE_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\PROPERTY_FIX_FITTINGS_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\PROPERTY_FIX_FITTINGS_TAB_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\UNITS_CRITERIA_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\UNITS_OBJ_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\UNITS_TYPE_TABLE.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_CUST_DETAIL_LIST.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_CUST_DETAIL_OBJ.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_CUST_DETAIL_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_OFFER_DETAIL_TYP.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_OFFER_DETAIL_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_OFFER_HEADER_TYP.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_OFFER_HEADER_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_OFFER_MILESTONE_DETAIL_TYP.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_OFFER_MILESTONE_DETAIL_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_PROPERTY_MILE_TYP.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_PROPERTY_MILE_TYPE.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_RECEIPT_OBJ.sql
@C:\Users\DineshkumarP\Desktop\PROD\XXPM_RECEIPT_TYPE.sql
