--------------------------------------------------------
--  File created - Monday-October-26-2020   
--------------------------------------------------------
@C:\Users\Balaji\Documents\sale_backup\CANCELLATION_NOTIFICATION.sql
@C:\Users\Balaji\Documents\sale_backup\CREATE_PAYMENT_LINES.sql
@C:\Users\Balaji\Documents\sale_backup\GET_AREA_DETAILS.sql
@C:\Users\Balaji\Documents\sale_backup\GET_USER_DETAILS.sql
@C:\Users\Balaji\Documents\sale_backup\INV_CNCL_AMT.sql
@C:\Users\Balaji\Documents\sale_backup\LOAD_INVOICE.sql
@C:\Users\Balaji\Documents\sale_backup\OFFER_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\OFFER_HDR.sql
@C:\Users\Balaji\Documents\sale_backup\OFFER_MILESTONE.sql
@C:\Users\Balaji\Documents\sale_backup\RELEASE_BLOCK.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_BOOKING_DATES.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_BUILDINGS.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_BUILDINGS2.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_BUILDINGS3.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_BUILD_FEATUREES.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_DUPINVOICES.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_INOVICE_BOOKING_NUMBER.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_INVOICES.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_INVOICE_DETAILS.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_PROPERTY_FEATUREES.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_RECEIPTDATES.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_STATUS.sql
@C:\Users\Balaji\Documents\sale_backup\UPDATE_UNIT_FEATUREES.sql
@C:\Users\Balaji\Documents\sale_backup\UPDBLOCKSTATUS.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_AREA_VALIDATIONS.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_CREATE_BOOKING.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PAYMENT_MILESTONES_CREATION.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PAYMENT_MILESTONES_VAL.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALES_MILESTONES_VAL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_APPROVAL_UPD_RESPONSE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CHANGE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CREATE_AUTO_BILLING.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CREATE_INVOICE_TXN.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_FUNC_PROC.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INSERT_BOOKING_MS_DEBIT_MEMO.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_JS_UNIT_MASTER_VALIDATION.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_BOOKING.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_DETAIL_SERVICE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_HEADER_SERVICE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_MILESTONE_DETAIL_SERVICE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROC.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROC_BLOCKING.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROC_BOOKING.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROC_PRICELIST_REVISION.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROC_UPDATE_CUST_ID.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROC_UPDATE_ORG_ID.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MILE_SERVICE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_PCUST_NUM.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_UPDATE_PROC.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UPDATE_MILESTONE_STATUS.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_SYNC_CUSTOMER.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_SYNC_CUSTOMER_CONTACT.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_SYNC_CUSTOMER_SITE.sql
@C:\Users\Balaji\Documents\sale_backup\update_milestone_numbers.sql
