--------------------------------------------------------
--  DDL for Table XXPM_BLOCK_HEADER
--------------------------------------------------------

  CREATE TABLE "XXPM_BLOCK_HEADER" 
   (	"BLOCK_ID" NUMBER, 
	"BLOCK_NUMBER" VARCHAR2(30), 
	"BLOCK_DATE" DATE, 
	"BLOCK_TYPE" VARCHAR2(30), 
	"BLOCKED_BY" VARCHAR2(60), 
	"ORG_ID" NUMBER, 
	"STATUS" VARCHAR2(60), 
	"DESCRIPTION" VARCHAR2(4000), 
	"FUNC_ID" NUMBER DEFAULT 18, 
	"FLOW_STATUS" VARCHAR2(60), 
	"FLOW_LEVEL" NUMBER, 
	"FLOW_WITH" NUMBER, 
	"USER_GRP_ID" NUMBER, 
	"RECEIPT_YN" VARCHAR2(1), 
	"OFFER_HDR_ID" NUMBER, 
	"CUST_ID" NUMBER, 
	"CUST_SITE_ID" NUMBER, 
	"VALID_UPTO" DATE, 
	"EXTN_REASON" VARCHAR2(60), 
	"EXTN_COUNT" NUMBER, 
	"CREATED_BY" VARCHAR2(60), 
	"CREATED_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(60), 
	"LEAD_ID" NUMBER, 
	"USAGE" VARCHAR2(30), 
	"PROPERTY_ID" NUMBER
   )
