--------------------------------------------------------
--  DDL for Table XXPM_LEASE_AGREEMENT
--------------------------------------------------------

  CREATE TABLE "XXPM_LEASE_AGREEMENT" 
   (	"LEASE_AGREEMENT_ID" NUMBER, 
	"FUNC_ID" NUMBER, 
	"BOOKING_ID" NUMBER, 
	"LEASE_NUMBER" VARCHAR2(60), 
	"LEASE_DATE" DATE, 
	"ORG_ID" NUMBER, 
	"TENANCY_CON_DOC_NO" VARCHAR2(240), 
	"STATUS" VARCHAR2(60), 
	"USAGE" VARCHAR2(30), 
	"DESCRIPTION" VARCHAR2(240), 
	"FLOW_STATUS" VARCHAR2(60), 
	"FLOW_LEVEL" NUMBER, 
	"FLOW_WITH" NUMBER, 
	"USER_GRP_ID" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(60)
   )
