--------------------------------------------------------
--  DDL for Type FEATURES_OBJ_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "FEATURES_OBJ_TYPE" force AS OBJECT (
    FEATURE_ID	NUMBER,
    PROPERTY_NUMBER VARCHAR2(60),
    PROPERTY_ID NUMBER,
    BUILD_NUMBER VARCHAR2(60),
    BUILD_ID NUMBER,
    UNIT_NUMBER VARCHAR2(60),
    UNIT_ID NUMBER,
    FEATURE_TYPE VARCHAR2(60),
	DESCRIPTION	VARCHAR2(4000),
    FEATURE_CONDITION VARCHAR2(60),
    UOM VARCHAR2(60),
    VALUE VARCHAR2(20),
    QUANTITY VARCHAR2(20),
    RATE VARCHAR2(20),
	CONSTRUCTOR FUNCTION FEATURES_OBJ_TYPE RETURN SELF AS RESULT);
