--------------------------------------------------------
--  DDL for Procedure XXPM_OFFER_MILESTONE_DETAIL_SERVICE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "XXPM_OFFER_MILESTONE_DETAIL_SERVICE" (
    XXPM_OFFER_MILESTONE_DETAIL_TYPE_T XXPM_OFFER_MILESTONE_DETAIL_TYPE,
    p_offer_milestone_id out number)
AS

V_TEMP NUMBER;
  cursor c1(p_offer_milestone_id NUMBER)
  is
    select 1 
    from XXPM_OFFER_MILESTONE_DETAIL 
    where OFFER_MS_DTL_ID = p_offer_milestone_id;

BEGIN
  FOR i IN 1..XXPM_OFFER_MILESTONE_DETAIL_TYPE_T.count
  LOOP
  
 
  SELECT XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).OFFER_MS_DTL_ID INTO p_offer_milestone_id FROM DUAL;
      
      OPEN C1(p_offer_milestone_id);
      FETCH C1 INTO V_TEMP;
        IF C1%NOTFOUND 
        THEN
            select OFFER_MS_DTL_ID.NEXTVAL INTO p_offer_milestone_id from dual;
        ELSE
            NULL;
        END IF;
      CLOSE C1;
  
    MERGE INTO XXPM_OFFER_MILESTONE_DETAIL a USING
    (SELECT 
	    p_offer_milestone_id                                      OFFER_MS_DTL_ID    ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).OFFER_HDR_ID        OFFER_HDR_ID       ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).MS_DTL_ID           MS_DTL_ID          ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).PL_MOD_ID           PL_MOD_ID          ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).SEQ_NUMBER          SEQ_NUMBER         ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).INSTALLMENT_TYPE    INSTALLMENT_TYPE   ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).INSTALLMENT_PCT     INSTALLMENT_PCT    ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).INSTALLMENT_AMOUNT  INSTALLMENT_AMOUNT ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).CHARGE_TYPE         CHARGE_TYPE        ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).PAYMENT_TERM        PAYMENT_TERM       ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).REMARKS             REMARKS            ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).DUE_DAYS            DUE_DAYS           ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).DUE_DAYS_FROM       DUE_DAYS_FROM      ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).DUE_DATE            DUE_DATE           ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE_CATEGORY  ATTRIBUTE_CATEGORY ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE1          ATTRIBUTE1         ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE2          ATTRIBUTE2         ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE3          ATTRIBUTE3         ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE4          ATTRIBUTE4         ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE5          ATTRIBUTE5         ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE6          ATTRIBUTE6         ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE7          ATTRIBUTE7         ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE8          ATTRIBUTE8         ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE9          ATTRIBUTE9         ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE10         ATTRIBUTE10        ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).CREATED_BY          CREATED_BY         ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).CREATION_DATE       CREATION_DATE      ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).LAST_UPDATED_BY     LAST_UPDATED_BY    ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).LAST_UPDATE_DATE    LAST_UPDATE_DATE   ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).LAST_UPDATE_LOGIN   LAST_UPDATE_LOGIN  ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).MILESTONE_TYPE      MILESTONE_TYPE     ,
	  XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).UOM                 UOM                ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).QUANTITY            QUANTITY           ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).RATE                RATE               ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).WAVE_OFF            WAVE_OFF           ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).INSTALLMENT_METHOD  INSTALLMENT_METHOD ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).INSTALLMENT_EVENT   INSTALLMENT_EVENT  ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).PERIOD_OCCURENCE    PERIOD_OCCURENCE   ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).PERIOD_VALUES       PERIOD_VALUES      ,
      XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).PERIOD_DURATION     PERIOD_DURATION    
    FROM DUAL
    ) b ON (a.OFFER_MS_DTL_ID = b.OFFER_MS_DTL_ID)
  WHEN MATCHED THEN
    UPDATE
    SET OFFER_HDR_ID       = b.OFFER_HDR_ID        ,
      MS_DTL_ID          = b.MS_DTL_ID           ,
      PL_MOD_ID          = b.PL_MOD_ID           ,
      SEQ_NUMBER         = b.SEQ_NUMBER          ,
      INSTALLMENT_TYPE   = b.INSTALLMENT_TYPE    ,
      INSTALLMENT_PCT    = b.INSTALLMENT_PCT     ,
      INSTALLMENT_AMOUNT = b.INSTALLMENT_AMOUNT  ,
      CHARGE_TYPE        = b.CHARGE_TYPE         ,
      PAYMENT_TERM       = b.PAYMENT_TERM        ,
      REMARKS            = b.REMARKS             ,
      DUE_DAYS           = b.DUE_DAYS            ,
      DUE_DAYS_FROM      = b.DUE_DAYS_FROM       ,
      DUE_DATE           = b.DUE_DATE            ,
      ATTRIBUTE_CATEGORY = b.ATTRIBUTE_CATEGORY  ,
      ATTRIBUTE1         = b.ATTRIBUTE1          ,
      ATTRIBUTE2         = b.ATTRIBUTE2          ,
      ATTRIBUTE3         = b.ATTRIBUTE3          ,
      ATTRIBUTE4         = b.ATTRIBUTE4          ,
      ATTRIBUTE5         = b.ATTRIBUTE5          ,
      ATTRIBUTE6         = b.ATTRIBUTE6          ,
      ATTRIBUTE7         = b.ATTRIBUTE7          ,
      ATTRIBUTE8         = b.ATTRIBUTE8          ,
      ATTRIBUTE9         = b.ATTRIBUTE9          ,
      ATTRIBUTE10        = b.ATTRIBUTE10         ,
      CREATED_BY         = b.CREATED_BY          ,
      CREATION_DATE      = b.CREATION_DATE       ,
      LAST_UPDATED_BY    = b.LAST_UPDATED_BY     ,
      LAST_UPDATE_DATE   = b.LAST_UPDATE_DATE    ,
      LAST_UPDATE_LOGIN  = b.LAST_UPDATE_LOGIN   ,  
      MILESTONE_TYPE     = b.MILESTONE_TYPE      ,
      UOM                = b.UOM                 ,
      QUANTITY           = b.QUANTITY            ,
      RATE               = b.RATE                ,
      WAVE_OFF           = b.WAVE_OFF            ,
      INSTALLMENT_METHOD = b.INSTALLMENT_METHOD  ,
      INSTALLMENT_EVENT  = b.INSTALLMENT_EVENT   ,
      PERIOD_OCCURENCE   = b.PERIOD_OCCURENCE    ,
	  PERIOD_VALUES      = b.PERIOD_VALUES       ,
	  PERIOD_DURATION    = b.PERIOD_DURATION   
    WHEN NOT MATCHED THEN
    INSERT
      (
        OFFER_MS_DTL_ID      ,
		OFFER_HDR_ID         ,
		MS_DTL_ID            ,
		PL_MOD_ID            ,
		SEQ_NUMBER           ,
		INSTALLMENT_TYPE     ,
		INSTALLMENT_PCT      ,
		INSTALLMENT_AMOUNT   ,
		CHARGE_TYPE          ,
		PAYMENT_TERM         ,
		REMARKS              ,
		DUE_DAYS             ,
		DUE_DAYS_FROM        ,
		DUE_DATE             ,
		ATTRIBUTE_CATEGORY   ,
		ATTRIBUTE1           ,
		ATTRIBUTE2           ,
		ATTRIBUTE3           ,
		ATTRIBUTE4           ,
		ATTRIBUTE5           ,
		ATTRIBUTE6           ,
		ATTRIBUTE7           ,
		ATTRIBUTE8           ,
		ATTRIBUTE9           ,
		ATTRIBUTE10          ,
		CREATED_BY           ,
		CREATION_DATE        ,
		LAST_UPDATED_BY      ,
		LAST_UPDATE_DATE     ,
		LAST_UPDATE_LOGIN    ,
		MILESTONE_TYPE       ,
        UOM                  ,
        QUANTITY             ,
        RATE                 ,
        WAVE_OFF             ,
        INSTALLMENT_METHOD   ,
        INSTALLMENT_EVENT    ,
		PERIOD_OCCURENCE     ,
        PERIOD_VALUES        ,
		PERIOD_DURATION   
      )
      VALUES
      (
        p_offer_milestone_id,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).OFFER_HDR_ID        ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).MS_DTL_ID           ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).PL_MOD_ID           ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).SEQ_NUMBER          ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).INSTALLMENT_TYPE    ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).INSTALLMENT_PCT     ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).INSTALLMENT_AMOUNT  ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).CHARGE_TYPE         ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).PAYMENT_TERM        ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).REMARKS             ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).DUE_DAYS            ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).DUE_DAYS_FROM       ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).DUE_DATE            ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE_CATEGORY  ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE1          ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE2          ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE3          ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE4          ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE5          ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE6          ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE7          ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE8          ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE9          ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).ATTRIBUTE10         ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).CREATED_BY          ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).CREATION_DATE       ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).LAST_UPDATED_BY     ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).LAST_UPDATE_DATE    ,
        XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).LAST_UPDATE_LOGIN   ,
		XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).MILESTONE_TYPE      ,
		XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).UOM                 ,
		XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).QUANTITY            ,
		XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).RATE                ,
		XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).WAVE_OFF            ,
		XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).INSTALLMENT_METHOD  ,
		XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).INSTALLMENT_EVENT   ,
		XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).PERIOD_OCCURENCE    ,
		XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).PERIOD_VALUES       ,
		XXPM_OFFER_MILESTONE_DETAIL_TYPE_T(i).PERIOD_DURATION   
      );
    COMMIT;
    
  END LOOP;
EXCEPTION
WHEN OTHERS THEN
  RAISE;
END XXPM_OFFER_MILESTONE_DETAIL_SERVICE;
