--------------------------------------------------------
--  File created - Monday-October-26-2020   
--------------------------------------------------------
@C:\Users\Balaji\Documents\sale_backup\TO_JSON.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_EXCELDATA_MIGRATION_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALE_INVOICES.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALE_RECEIPTS_OPEN_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALE_RECEIPTS_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_EMAIL_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_NODE_SCHEDULER.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SCHEDULE_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_UTIL_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPACA_HRMS_REPORT_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPL_PROPERTY_LEASE_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_ACTIVITY_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CHANGE_PROCESS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_MASTER_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AUTO_BILLING_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BILL_INVOICE_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DASHBOARD.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOK_MS_REV_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CANCELLATION_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CARPARK_MASTER_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_DATALOAD_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_DM_LIB_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_FEATURE_MASTER_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_FIX_FIT_MASTER_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_DETAIL_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_MASTER_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_NOTIFICATION.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_IFC_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_RENEW_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_REV_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PCS_APPROVAL_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PCS_DATA_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_MODIFIER_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_QUALIFIER_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PRICELIST_DETAIL_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PRICELIST_MASTER_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PRISM.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_ACCOUNT_SYNC.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECOMMEND_REV_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_SALESFORCE_OUTBOUND_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_SCHEDULER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_TRANSACTION_COUNT.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNIT_MASTER_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UTILITY_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UTIL_PACKAGE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPRISM_REPORT_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXREP_REPORT_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\XXSF_AGENT_SYNC.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_INTEGRATION_PKG.sql
@C:\Users\Balaji\Documents\sale_backup\TO_JSON_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_EXCELDATA_MIGRATION_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALE_INVOICES_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALE_RECEIPTS_OPEN_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALE_RECEIPTS_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_EMAIL_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_NODE_SCHEDULER_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SCHEDULE_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_UTIL_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPACA_HRMS_REPORT_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPL_PROPERTY_LEASE_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_ACTIVITY_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CHANGE_PROCESS_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_MASTER_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AUTO_BILLING_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BILL_INVOICE_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DASHBOARD_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOK_MS_REV_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CANCELLATION_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CARPARK_MASTER_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_DATALOAD_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_DM_LIB_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_FEATURE_MASTER_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_FIX_FIT_MASTER_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_DETAIL_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_MASTER_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_NOTIFICATION_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_IFC_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_RENEW_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_REV_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PCS_APPROVAL_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PCS_DATA_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_MODIFIER_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_QUALIFIER_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PRICELIST_DETAIL_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PRICELIST_MASTER_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PRISM_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_ACCOUNT_SYNC_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECOMMEND_REV_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_SALESFORCE_OUTBOUND_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_SCHEDULER_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_TRANSACTION_COUNT_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNIT_MASTER_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UTILITY_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UTIL_PACKAGE_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPRISM_REPORT_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXREP_REPORT_PKG_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSF_AGENT_SYNC_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_INTEGRATION_PKG_1.sql
