--------------------------------------------------------
--  DDL for Procedure CREATE_PAYMENT_LINES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CREATE_PAYMENT_LINES" 
AS

  CURSOR cur_sales_milestones
  IS
    SELECT rowid,
      MS_DTL_ID,
      MS_HDR_ID,
MILESTONE_NUMBER,
SEQ_NUMBER,
INSTALLMENT_TYPE,
INSTALLMENT_PCT,
CHARGE_TYPE,
PAYMENT_TERM,
REMARKS,
DUE_DAYS,
DUE_DAYS_FROM,
PROJ_MS_ID,
 DUE_DATE,
REVISION,
REVISION_DATE,
REVISED_BY,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
LAST_UPDATE_LOGIN,
INSTALLMENT_METHOD,
INSTALLMENT_EVENT,
PERIOD_OCCURENCE,
PERIOD_VALUES,
PERIOD_DURATION
BATCH_ID,
INTERFACE_STATUS_FLAG,
INTERFACE_ID,
ERR_MSG,
ERR_DESCRIPTION,
VALIDATED_BY,
VALIDATED_DATE,
PROCESSED_BY,
PROCESSED_DATE,
ACTION_FLAG,
PROCESS_FLAG,
INSERT_HISTORY_FLAG
    FROM XXDM_MILESTONE_DTL
    WHERE INTERFACE_STATUS_FLAG = 'V' ;
    

    

BEGIN



  FOR i IN CUR_SALES_MILESTONES
  LOOP
  BEGIN
    INSERT
    INTO xxpm_milestone_dtl
      (
      MS_DTL_ID,
MS_HDR_ID,
SEQ_NUMBER,
INSTALLMENT_TYPE,
INSTALLMENT_PCT,
CHARGE_TYPE,
PAYMENT_TERM,
REMARKS,
DUE_DAYS,
DUE_DAYS_FROM,
PROJ_MS_ID,
DUE_DATE,
REVISION,
REVISION_DATE,
REVISED_BY,
ATTRIBUTE_CATEGORY,
ATTRIBUTE1,
ATTRIBUTE2,
ATTRIBUTE3,
ATTRIBUTE4,
ATTRIBUTE5,
ATTRIBUTE6,
ATTRIBUTE7,
ATTRIBUTE8,
ATTRIBUTE9,
ATTRIBUTE10,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
LAST_UPDATE_LOGIN,
INSTALLMENT_METHOD,
INSTALLMENT_EVENT,
PERIOD_OCCURENCE,
PERIOD_VALUES
      )
     VALUES
      (
        XXPM_MS_DTL_ID_S.NEXTVAL,
i.MS_HDR_ID,
i.SEQ_NUMBER,
i.INSTALLMENT_TYPE,
i.INSTALLMENT_PCT,
i.CHARGE_TYPE,
i.PAYMENT_TERM,
i.REMARKS,
null,
null,
null,
i.DUE_DATE,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
null,
'anonymous',
SYSDATE,
'anonymous',
SYSDATE,
'anonymous',
i.INSTALLMENT_METHOD,
i.INSTALLMENT_EVENT,
i.PERIOD_OCCURENCE,
null);
    UPDATE XXDM_MILESTONE_DTL
    SET INTERFACE_STATUS_FLAG      ='P'
    WHERE milestone_number = i.milestone_number
    AND rowid            = i.rowid;



    EXCEPTION
    WHEN OTHERS THEN
              --SQLCODE;
      -- SUBSTR (SQLERRM, 1, 2000);
        UPDATE XXDM_MILESTONE_DTL set INTERFACE_STATUS_FLAG='F'
        WHERE milestone_number = i.milestone_number
        --and error_msg=SQLCODE
        --and error_description=SUBSTR (SQLERRM, 1, 2000)
        AND rowid  = i.rowid;
           dbms_output.put_line('CURSOR1'||SQLCODE);
             --dbms_output.put_line('CURSOR2'||SUBSTR (SQLERRM, 1, 2000));
    END;
    END LOOP; 
  COMMIT;

END CREATE_PAYMENT_LINES;
