--------------------------------------------------------
--  File created - Monday-October-26-2020   
--------------------------------------------------------
@C:\Users\Balaji\Documents\sale_backup\AREA_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\AREA_TYPE_TABLE.sql
@C:\Users\Balaji\Documents\sale_backup\CAR_PAK_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\CAR_PARK_TYPE_TABLE.sql
@C:\Users\Balaji\Documents\sale_backup\FEATURES_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\FEATURES_TABLE_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\MILESTONE_HEADER_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\MILESTONE_HEADER_TABLE_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\MILESTONE_LINE_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\MILESTONE_LINE_TABLE_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\OWNER_DTLE_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\OWNER_DTLE_TAB_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\PL_HEADER_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\PL_HEADER_TABLE_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\PL_LINE_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\PL_LINE_TABLE_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\PL_MODIFIERS_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\PL_MODIFIERS_TABLE_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\PL_QUALIFIERS_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\PL_QUALIFIERS_TABLE_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\PROPERTY_FIX_FITTINGS_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\PROPERTY_FIX_FITTINGS_TAB_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\UNITS_CRITERIA_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\UNITS_OBJ_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\UNITS_TYPE_TABLE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CUST_DETAIL_LIST.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CUST_DETAIL_OBJ.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CUST_DETAIL_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_DETAIL_TYP.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_DETAIL_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_HEADER_TYP.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_HEADER_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_MILESTONE_DETAIL_TYP.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_MILESTONE_DETAIL_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MILE_TYP.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MILE_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_OBJ.sql
