--------------------------------------------------------
--  File created - Monday-October-26-2020   
--------------------------------------------------------
@C:\Users\Balaji\Documents\sale_backup\ARSETUP_SEQ_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\AR_RECEIPT_S.sql
@C:\Users\Balaji\Documents\sale_backup\BOOKING_CUST_DTL_ID.sql
@C:\Users\Balaji\Documents\sale_backup\BOOKING_MS_DTL_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\CREDIT_MEMO_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\OFFER_DTL_HST_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\OFFER_DTL_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\OFFER_HDR_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\OFFER_HST_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\OFFER_MS_DTL_HST_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\OFFER_MS_DTL_ID.sql
@C:\Users\Balaji\Documents\sale_backup\PS_TXN_SEQ.sql
@C:\Users\Balaji\Documents\sale_backup\RECEIPT_DTL_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\SETUP_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\UNIT_TRANSFER_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_BATCH_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_ESM_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_IFACE_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_HIST_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_USER_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_ATTACH_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_ATTR_COMB_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_ATTR_GRP_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_ATTR_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_CL_RES_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_DATA_GROUP_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_DCOMB_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_DSEQ_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEX_CATG_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEX_DATA_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEX_FIELD_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEX_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_CL_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_LOOKUP_TYPE_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_LOOKUP_VALUE_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_MAIN_MENU_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_MENU_ACCESS_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_PARAM_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_ROLE_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SCHDL_ERR_ID_SEQ.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SCHEDULE_LIST_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SCHEDULE_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SUB_MENU_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_USER_GRP_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_USER_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_USER_LEVEL_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPL_OWNER_DTLE_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_ACTIVITY_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CNG_DLT_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CNG_HDR_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BILLING_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCK_DETAIL_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCK_HEADER_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCK_detail_S_1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CHARGE_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUSTOMER_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUSTOMER_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUST_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DETAIL_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DETAIL_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DTL_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_EVENTS_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_EVENTS_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HDR_REV_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HEADER_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HEADER_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_REV_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BUILD_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CANCEL_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CARPARK_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CONTACTS_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_DISCOUNT_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_ESCROW_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_EXTEN_CANCEL_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_FEATURES_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_FIXTURES_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INTERGRATION_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_HEADER_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_LINES_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_KEY_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_LEAD_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_LEASE_AGREEMENT_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_METER_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MODIFIERS_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IO_CUST_VISIT_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IO_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MS_DTL_H_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MS_DTL_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MS_HDR_H_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MS_HDR_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MS_REV_DTL_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MS_REV_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_NOTIFY_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_DETAIL_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_DETAIL_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_HEADER_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_HEADER_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_MILESTONE_DETAIL_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_MILESTONE_DTL_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_ORG_ASSIGNMENT_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_ORG_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_HEADER_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_HEADER_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_LINES_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_LINES_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_MODIFIERS_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_MODIFIERS_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_QUALIFIERS_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_QUALIFIERS_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PREMIUM_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PRICELIST_HISTORY_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_FIX_FITTINGS_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_FIX_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MORTGAGE_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_QUALIFIERS_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECOMMEND_CHARGE_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECOMMEND_DTL_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECOMMEND_HEADER_H_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECOMMEND_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_REGN_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_REVISION_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_REVISION_LINE_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNBLOCK_DETAIL_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNBLOCK_HEADER_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNIT_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXREP_BATCH_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_BANK_ACNT_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_BANK_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_CUST_CONTACT_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_CUST_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_CUST_SITE_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_EMP_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_LEAD_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_LOC_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_ORG_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_PROJ_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_PROJ_MS_ID.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_SP_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_TERM_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_VEND_CONTACT_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_VEND_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_VEND_SITE_ID_S.sql
@C:\Users\Balaji\Documents\sale_backup\XX_EMP_TEST_S.sql
