--------------------------------------------------------
--  File created - Monday-October-26-2020   
--------------------------------------------------------
@C:\Users\Balaji\Documents\sale_backup\AA_CP_V.sql
@C:\Users\Balaji\Documents\sale_backup\APPLY_CREDIT_MEMO_REFUND_V.sql
@C:\Users\Balaji\Documents\sale_backup\APPLY_CREDIT_MEMO_V.sql
@C:\Users\Balaji\Documents\sale_backup\SAMPLE_V.sql
@C:\Users\Balaji\Documents\sale_backup\SAMPLE_V1.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_USERS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_LOOKUP_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SALEFORCES_LOOKUP_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_APPROVAL_HIS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CHANGE_DLT_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CHANGE_HDR_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CHANGE_HEADER_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CHANGE_LINE_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BILLING_BOOKING_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BILLING_LINES_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BILLING_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCKING_DETAILS_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCKING_HEADER_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCKING_HEADER_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCKING_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCK_MILESTONE_DETAIL_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCK_RECEIPT_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKINGMSVIEW_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUSTOMER_DTL_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUSTOMER_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUSTOMER_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DASHBOARD_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DETAIL_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DETAIL_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HDR_SEARCH_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HEADER_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HEADER_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_INVOICE_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONE_DASHBOARD_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MOVE_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CANCELLATION_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CANCELLATION_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CANCEL_HDR_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CNCL_MORTGAGE_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_EXTEN_CANCEL_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_HANDOVER_HEADER_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_HO_CUSTVISIT_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_HO_KEYS_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONES_CREDIT_MEMO_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_DETAIL_H_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_HEADER_H_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_HEADER_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MODIFIERS_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IO_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_DETAIL_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_DETAIL_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_HEADERS_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PAYMENT_CHANGE_HDR_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PAYMENT_CHANGE_LINE_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PAYMENT_CHANGE_MS_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PAYMENT_CHARGE_DTL_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PAYMENT_CHARGE_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PRICELIST_HEADER_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PRICELIST_LINE_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MORTGAGE_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_QUALIFIERS_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_QUALIFIERS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_VXXPM_RECEIPT_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_REGISTRATION_HDR_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_REGISTRATION_MS_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_REGISTRATION_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_TERM_NOTI_PCS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNBLOCKING_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNIT_TRANSFER_BOOKING_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXSF_AGENTS_V.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_ORGANIZATIONS_V.sql
