--------------------------------------------------------
--  DDL for Trigger INVOICE_HDR_ACCOUNT_SYNC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "INVOICE_HDR_ACCOUNT_SYNC" 
AFTER INSERT or UPDATE ON XXPM_INVOICE_HDR_SYNC 
FOR EACH ROW  
DECLARE
BEGIN

XXPM_RECEIPT_ACCOUNT_SYNC.update_gl_invoice_header(:NEW.INVOICE_NUMBER, :NEW.GL_DATE, :NEW.CUSTOMER_TRX_ID);
null;
END INVOICE_HDR_ACCOUNT_SYNC;

ALTER TRIGGER "INVOICE_HDR_ACCOUNT_SYNC" ENABLE
