--------------------------------------------------------
--  DDL for Function IS_AMOUNT_LESS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "IS_AMOUNT_LESS" (P_OFF_HEADER_ID    NUMBER,
                                           P_PRICE_LIST    NUMBER,
                                           P_UNIT_ID          NUMBER)
		 RETURN VARCHAR2 AS

L_OFFER_MINI_PRICES NUMBER;
L_PL_MINI_PRICES 	NUMBER ;
L_OFFER_QTY 		NUMBER;
L_MINIAMT	 		NUMBER;
L_OFF_AMT           NUMBER;
L_RESULT			VARCHAR2(30):='NO';

BEGIN
BEGIN 
SELECT
   nvl(MIN_PRICE,0)  INTO L_OFFER_MINI_PRICES
FROM
    XXPM_OFFER_DETAIL
WHERE
    1=1
AND OFFER_HDR_ID = P_OFF_HEADER_ID;
EXCEPTION 
WHEN OTHERS THEN
L_OFFER_MINI_PRICES:=0;
END;

BEGIN
SELECT
    nvl(MIN_PRICE,0) INTO L_PL_MINI_PRICES
FROM
    XXPM_PL_LINES
WHERE
    1 = 1
AND PL_ID = P_PRICE_LIST
AND UNIT_ID = P_UNIT_ID;
EXCEPTION 
WHEN OTHERS THEN
L_PL_MINI_PRICES:=0;
END;

BEGIN
SELECT
    nvl(QUANTITY,0) INTO L_OFFER_QTY
FROM
    XXPM_OFFER_DETAIL
WHERE
    1=1
AND OFFER_HDR_ID = P_OFF_HEADER_ID;
EXCEPTION 
WHEN OTHERS THEN
L_OFFER_QTY:=0;
END;

BEGIN
SELECT  ((NVL(OFFER_AMOUNT,0)) - (NVL(DISC_AMOUNT,0))) INTO L_OFF_AMT
FROM XXPM_OFFER_DETAIL
WHERE OFFER_HDR_ID=P_OFF_HEADER_ID;
EXCEPTION 
WHEN OTHERS THEN
L_OFF_AMT:=0;
END;


IF(L_OFFER_MINI_PRICES=0) THEN
 L_MINIAMT := L_PL_MINI_PRICES*L_OFFER_QTY;
ELSE
 L_MINIAMT := L_OFFER_MINI_PRICES*L_OFFER_QTY;
END IF;

IF(L_OFF_AMT!=0 OR L_MINIAMT!=0) THEN
IF L_OFF_AMT>=L_MINIAMT THEN
-- user
L_RESULT :='YES';
ELSE
--manage
L_RESULT :='NO';
END IF;
ELSE
L_RESULT :='ERROR';
END IF;

RETURN L_RESULT;

END;
