--------------------------------------------------------
--  DDL for Procedure OFFER_HDR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "OFFER_HDR" (
    p_OFFER_HDR_ID           IN NUMBER,
    p_ORG_ID                 IN NUMBER,
    p_FUNC_ID                IN NUMBER,
    p_OFFER_NUMBER           IN VARCHAR2,
    p_OFFER_DATE             IN VARCHAR2,
    p_OFFER_FROM_DATE        IN VARCHAR2,
    p_OFFER_TO_DATE          IN VARCHAR2,
    p_PERFORMED_BY           IN VARCHAR2,
    p_REVISION_NO            IN NUMBER,
    p_REVISION_DATE          IN VARCHAR2,
    p_REVISED_BY             IN VARCHAR2,
    p_MS_HDR_ID              IN NUMBER,
    p_PL_ID                  IN NUMBER,
    p_OFFER_TYPE             IN VARCHAR2,
    p_LEAD_ID                IN NUMBER,
    p_CUSTOMER_ID            IN NUMBER,
    p_CUST_SITE_ID           IN NUMBER,
    p_CUSTOMER_NAME          IN VARCHAR2,
    p_CUSTOMER_PHONE_NO      IN VARCHAR2,
    p_CUSTOMER_COUNTRY       IN VARCHAR2,
    p_SALESMAN_ID            IN NUMBER,
    p_CURRENCY_CODE          IN VARCHAR2,
    p_CHECKLIST              IN VARCHAR2,
    p_TERMS_DESC             IN VARCHAR2,
    p_OBJECT_VERSION_NUMBER  IN VARCHAR2,
    p_OFFER_FLAG             IN VARCHAR2,
    p_TAX_CODE               IN VARCHAR2,
    p_PREV_BOOKING_ID        IN NUMBER,
    p_STATUS                 IN VARCHAR2,
    p_DESCRIPTION            IN VARCHAR2,
    p_FLOW_STATUS            IN VARCHAR2,
    p_FLOW_LEVEL             IN VARCHAR2,
    p_FLOW_WITH              IN VARCHAR2,
    p_USER_GRP_ID            IN NUMBER,
    p_ATTRIBUTE_CATEGORY     IN VARCHAR2,
    p_ATTRIBUTE1             IN VARCHAR2,
    p_ATTRIBUTE2             IN VARCHAR2,
    p_ATTRIBUTE3             IN VARCHAR2,
    p_ATTRIBUTE4             IN VARCHAR2,
    p_ATTRIBUTE5             IN VARCHAR2,
    p_ATTRIBUTE6             IN VARCHAR2,
    p_ATTRIBUTE7             IN VARCHAR2,
    p_ATTRIBUTE8             IN VARCHAR2,
    p_ATTRIBUTE9             IN VARCHAR2,
    p_ATTRIBUTE10            IN VARCHAR2,
    p_CREATED_BY             IN VARCHAR2,
    p_CREATION_DATE          IN VARCHAR2,
    p_LAST_UPDATED_BY        IN VARCHAR2,
    p_LAST_UPDATE_Date   IN VARCHAR2,
    p_LAST_UPDATE_LOGIN      IN VARCHAR2,
    p_OFFER_END_DATE         IN VARCHAR2,
    p_USAGE                  IN VARCHAR2,
    p_LEAD_SOURCE_CHANNEL    IN VARCHAR2,
    p_LEAD_SOURCE_NAME       IN VARCHAR2,
    p_VEND_ID                IN NUMBER,
    p_VEND_SITE_ID           IN NUMBER,
    p_VEND_CONTRACT_NO       IN VARCHAR2,
    p_PROPERTY_ID            IN NUMBER,
    p_EMAIL_ID               IN NUMBER,
    p_LEASE_AGREEMENT_ID     IN NUMBER,
    p_CAR_PARK_LEASE_AGRE_ID IN NUMBER,
    p_CUST_ACCEPT            IN VARCHAR2,
      status out varchar2 ,
      ErrorMessage out varchar2,
     out_offer_hdr out varchar2
  )
AS

  L_CURSOR SYS_REFCURSOR;

BEGIN
  INSERT
  INTO xxpm_offer_header
    (
      OFFER_HDR_ID,
      ORG_ID,
      FUNC_ID,
      OFFER_NUMBER,
      OFFER_DATE,
      OFFER_FROM_DATE,
      OFFER_TO_DATE,
      PERFORMED_BY,
      REVISION_NO,
      REVISION_DATE,
      REVISED_BY,
      MS_HDR_ID,
      PL_ID,
      OFFER_TYPE,
      LEAD_ID,
      CUSTOMER_ID,
      CUST_SITE_ID,
      CUSTOMER_NAME,
      CUSTOMER_PHONE_NO,
      CUSTOMER_COUNTRY,
      SALESMAN_ID,
      CURRENCY_CODE,
      CHECKLIST,
      TERMS_DESC,
      OBJECT_VERSION_NUMBER,
      OFFER_FLAG,
      TAX_CODE,
      PREV_BOOKING_ID,
      STATUS,
      DESCRIPTION,
      FLOW_STATUS,
      FLOW_LEVEL,
      FLOW_WITH,
      USER_GRP_ID,
      ATTRIBUTE_CATEGORY,
      ATTRIBUTE1,
      ATTRIBUTE2,
      ATTRIBUTE3,
      ATTRIBUTE4,
      ATTRIBUTE5,
      ATTRIBUTE6,
      ATTRIBUTE7,
      ATTRIBUTE8,
      ATTRIBUTE9,
      ATTRIBUTE10,
      CREATED_BY,
      CREATION_DATE,
      LAST_UPDATED_BY,
      LAST_UPDATE_DATE,
      LAST_UPDATE_LOGIN,
      OFFER_END_DATE,
      USAGE,
      LEAD_SOURCE_CHANNEL,
      LEAD_SOURCE_NAME,
      VEND_ID,
      VEND_SITE_ID,
      VEND_CONTRACT_NO,
      PROPERTY_ID,
      EMAIL_ID,
      LEASE_AGREEMENT_ID,
      CAR_PARK_LEASE_AGRE_ID,
      CUST_ACCEPT
    )
    VALUES
    (
      p_OFFER_HDR_ID,
      p_ORG_ID,
      p_FUNC_ID,
      p_OFFER_NUMBER,
      p_OFFER_DATE,
      p_OFFER_FROM_DATE,
      p_OFFER_TO_DATE,
      p_PERFORMED_BY,
      p_REVISION_NO,
      p_REVISION_DATE,
      p_REVISED_BY,
      p_MS_HDR_ID,
      p_PL_ID,
      p_OFFER_TYPE,
      p_LEAD_ID,
      p_CUSTOMER_ID,
      p_CUST_SITE_ID,
      p_CUSTOMER_NAME,
      p_CUSTOMER_PHONE_NO,
      p_CUSTOMER_COUNTRY,
      p_SALESMAN_ID,
      p_CURRENCY_CODE,
      p_CHECKLIST,
      p_TERMS_DESC,
      p_OBJECT_VERSION_NUMBER,
      p_OFFER_FLAG,
      p_TAX_CODE,
      p_PREV_BOOKING_ID,
      p_STATUS,
      p_DESCRIPTION,
      p_FLOW_STATUS,
      p_FLOW_LEVEL,
      p_FLOW_WITH,
      p_USER_GRP_ID,
      p_ATTRIBUTE_CATEGORY,
      p_ATTRIBUTE1,
      p_ATTRIBUTE2,
      p_ATTRIBUTE3,
      p_ATTRIBUTE4,
      p_ATTRIBUTE5,
      p_ATTRIBUTE6,
      p_ATTRIBUTE7,
      p_ATTRIBUTE8,
      p_ATTRIBUTE9,
      p_ATTRIBUTE10,
      p_CREATED_BY,
      p_CREATION_DATE,
      p_LAST_UPDATED_BY,
      p_LAST_UPDATE_DATE,
      p_LAST_UPDATE_LOGIN,
      p_OFFER_END_DATE,
      p_USAGE,
      p_LEAD_SOURCE_CHANNEL,
      p_LEAD_SOURCE_NAME,
      p_VEND_ID,
      p_VEND_SITE_ID,
      p_VEND_CONTRACT_NO,
      p_PROPERTY_ID,
      p_EMAIL_ID,
      p_LEASE_AGREEMENT_ID,
      p_CAR_PARK_LEASE_AGRE_ID,
      p_CUST_ACCEPT
    );

  status :='Success';
  ErrorMessage := null;
  out_offer_hdr :=p_OFFER_HDR_ID;
  OPEN L_CURSOR FOR select status ,ErrorMessage , out_offer_hdr from dual;
    APEX_JSON.WRITE(L_CURSOR);
  COMMIT;

   exception when others then
    out_offer_hdr:= null;
  status :='Failed';
  ErrorMessage :=substr (sqlerrm, 1, 2000);
  OPEN L_CURSOR FOR select status ,ErrorMessage , out_offer_hdr from dual;
    APEX_JSON.WRITE(L_CURSOR);
  COMMIT;
END ;
