--------------------------------------------------------
--  DDL for Trigger RECEIPT_LINE_ACCOUNT_SYNC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "RECEIPT_LINE_ACCOUNT_SYNC" 
AFTER INSERT or UPDATE ON XXPM_RECEIPT_APP_ACC_REPORT 
FOR EACH ROW  
DECLARE
BEGIN
XXPM_RECEIPT_ACCOUNT_SYNC.update_gl_receipt_line(
:NEW.RECEIPT_NUMBER,
:NEW.TRX_NUMBER,
:NEW.GL_DATE,
:NEW.CUSTOMER_TRX_ID,
:NEW.RECEIVABLE_APPLICATION_ID
); 
END RECEIPT_LINE_ACCOUNT_SYNC;

ALTER TRIGGER "RECEIPT_LINE_ACCOUNT_SYNC" ENABLE
