--------------------------------------------------------
--  DDL for Type UNITS_OBJ_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "UNITS_OBJ_TYPE" force AS OBJECT (
    unit_id             number, 
    property_id         number, 
    build_id            number,
    build_number        varchar2(60),
    property_number  varchar2(60),
    unit_name           varchar2(240),
    unit_name_tl        varchar2(240),
    unit_number         varchar2(60),
    unit_shortcode      varchar2(60),
    func_id             number,
    org_id              number,
    parent_unit_id      number,
    doc_ref_number_1    varchar2(60),
    doc_ref_number_2    varchar2(60),
    doc_ref_number_3    varchar2(60),
    floor_number        varchar2(60),
    no_of_rooms         number,
    unit_type           varchar2(60),
    area_type           varchar2(60),
    view_type           varchar2(60),
    chargeable_area     number,
    uom                 varchar2(60),
    currency_code       varchar2(3),
    base_rate           number,
    total_rate          number,
    purchase_amount     number,
    status              varchar2(60),
    unit_class          varchar2(60),
    unit_category       varchar2(60),
    vend_id number,
    description varchar2(4000),
    active_yn varchar2(1),
    saleable_yn varchar2(1),
    leaseable_yn varchar2(1),
    sale_available_yn varchar2(1),
    lease_available_yn varchar2(1),
    free_hold_yn varchar2(1),
    lease_hold_yn varchar2(1),
    list_for_brokers varchar2(1),
    list_for_internal varchar2(1),
    allot_type varchar2(30),
  CONSTRUCTOR FUNCTION Units_Obj_Type RETURN SELF AS RESULT);
