--------------------------------------------------------
--  DDL for Procedure UPDATE_PROPERTY_FEATUREES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "UPDATE_PROPERTY_FEATUREES" 
AS
  CURSOR cur_insert
  IS
    SELECT PROPERTY_ID,PROPERTY_NUMBER FROM XXPM_PROPERTY_MASTER;
BEGIN
  FOR i IN cur_insert
  LOOP
    UPDATE XXDM_PROPERTY_FEATURES SET PROPERTY_ID=i.PROPERTY_ID WHERE PROPERTY_NUMBER=i.PROPERTY_NUMBER ;
  END LOOP;
  COMMIT;
END UPDATE_PROPERTY_FEATUREES;
