--------------------------------------------------------
--  DDL for Table XXDM_INTERFACE
--------------------------------------------------------

  CREATE TABLE "XXDM_INTERFACE" 
   (	"BATCH_ID" NUMBER, 
	"IFACE_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(240), 
	"UPLOADED_FILE" BLOB, 
	"UPLOAD_FROM" NUMBER, 
	"STATUS" VARCHAR2(30), 
	"UPLOADED_BY" VARCHAR2(100), 
	"UPLOAD_DATE" DATE, 
	"VALIDATED_BY" VARCHAR2(100), 
	"VALIDATE_DATE" DATE, 
	"PROCESSED_BY" VARCHAR2(100), 
	"PROCESS_DATE" DATE, 
	"CREATED_BY" VARCHAR2(100), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" VARCHAR2(100)
   )
