--------------------------------------------------------
--  DDL for Table XXDM_PROPERTY_CARPARKS_BCK0309
--------------------------------------------------------

  CREATE TABLE "XXDM_PROPERTY_CARPARKS_BCK0309" 
   (	"CARPARK_ID" VARCHAR2(60), 
	"UNIT_NUMBER" VARCHAR2(60), 
	"CP_UNIT_NUMBER" VARCHAR2(60), 
	"ALLOT_TYPE" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"BATCH_ID" NUMBER, 
	"INTERFACE_STATUS_FLAG" VARCHAR2(1), 
	"INTERFACE_ID" NUMBER, 
	"ERR_MSG" VARCHAR2(2000), 
	"ERR_DESCRIPTION" VARCHAR2(2000), 
	"VALIDATED_BY" VARCHAR2(60), 
	"VALIDATED_DATE" TIMESTAMP (6), 
	"PROCESSED_BY" VARCHAR2(60), 
	"PROCESSED_DATE" TIMESTAMP (6), 
	"UNIT_ID" NUMBER, 
	"CP_UNIT_ID" NUMBER
   )
