--------------------------------------------------------
--  DDL for Table XXFND_FLEXS_FIELDS
--------------------------------------------------------

  CREATE TABLE "XXFND_FLEXS_FIELDS" 
   (	"FLEX_FIELD_ID" NUMBER, 
	"FLEX_CATG_ID" NUMBER, 
	"FLEX_ID" NUMBER, 
	"SEQ_NUMBER" NUMBER, 
	"FLEX_COLUMN" VARCHAR2(30), 
	"DISPLAY_NAME" VARCHAR2(30), 
	"FLEX_LENGTH" NUMBER, 
	"DISPLAY_SIZE" NUMBER, 
	"DATA_TYPE" VARCHAR2(1), 
	"VALUE_SET_ID" NUMBER, 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
