--------------------------------------------------------
--  DDL for Table XXFND_FUNCTIONS
--------------------------------------------------------

  CREATE TABLE "XXFND_FUNCTIONS" 
   (	"FUNC_ID" NUMBER, 
	"FUNC_NAME" VARCHAR2(60), 
	"FUNC_SHORT_CODE" VARCHAR2(30), 
	"AUTO_NUMBER_YN" VARCHAR2(1), 
	"PREFIX" VARCHAR2(10), 
	"NEXT_NUMBER" NUMBER, 
	"PAGE_PATH" VARCHAR2(500), 
	"ACTIVE_YN" VARCHAR2(1), 
	"INACTIVE_ON" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"FUNC_TYPE" VARCHAR2(30)
   )
