--------------------------------------------------------
--  DDL for Table XXFND_FUNC_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "XXFND_FUNC_ATTACHMENT" 
   (	"ATTACH_ID" NUMBER, 
	"FUNC_ID" VARCHAR2(30), 
	"FUNC_REF_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(4000), 
	"FILE_NAME" VARCHAR2(240), 
	"FILE_TYPE" VARCHAR2(100), 
	"ATTACHMENT" BLOB, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"FUNC_TABLE_NAME" VARCHAR2(60)
   )
