--------------------------------------------------------
--  DDL for Table XXFND_SETUP_DETAIL
--------------------------------------------------------

  CREATE TABLE "XXFND_SETUP_DETAIL" 
   (	"SETUP_ID" NUMBER, 
	"USER_NAME" VARCHAR2(60), 
	"PASS_WORD" VARCHAR2(60), 
	"HOLD_DAY" NUMBER, 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" NUMBER, 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	"ATTRIBUTE9" DATE, 
	"ATTRIBUTE10" DATE, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"INVOICE_TXN_SOURCE_NAME" VARCHAR2(200), 
	"INVOICE_TXN_SOURCE_TYPE" VARCHAR2(200), 
	"CREDIT_TXN_SOURCE_NAME" VARCHAR2(200), 
	"CREDIT_TXN_SOURCE_TYPE" VARCHAR2(200), 
	"DEBIT_TXN_SOURCE_NAME" VARCHAR2(200), 
	"DEBIT_TXN_SOURCE_TYPE" VARCHAR2(200), 
	"FUSION_DOMAIN" VARCHAR2(240), 
	"FUSION_USERNAME" VARCHAR2(240), 
	"FUSION_PASSWORD" VARCHAR2(240)
   )
