--------------------------------------------------------
--  DDL for Table XXFND_SUB_MENU
--------------------------------------------------------

  CREATE TABLE "XXFND_SUB_MENU" 
   (	"SUB_MENU_ID" NUMBER, 
	"SUB_MENU_NAME" VARCHAR2(100), 
	"SUB_MENU_NAME_DISP" VARCHAR2(240), 
	"SUB_MENU_NAME_DISP_TL" VARCHAR2(240), 
	"SUB_MENU_ORDER" NUMBER, 
	"MAIN_MENU_ID" NUMBER, 
	"FUNC_ID" NUMBER, 
	"MENU_PARAMS" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"MENU_ICON" VARCHAR2(240)
   )
