--------------------------------------------------------
--  DDL for Table XXFND_REPORT_PARAMS
--------------------------------------------------------

  CREATE TABLE "XXFND_REPORT_PARAMS" 
   (	"PARAM_ID" NUMBER, 
	"FUNC_ID" NUMBER, 
	"SEQ_NUMBER" NUMBER, 
	"PARAM_NAME" VARCHAR2(30), 
	"PARAM_TABLE" VARCHAR2(60), 
	"PARAM_COLUMN" VARCHAR2(60), 
	"PARAM_DISP_COLUMN" VARCHAR2(60), 
	"PARAM_LOOKUP_TYPE" VARCHAR2(60), 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"DATA_TYPE" VARCHAR2(30), 
	"TOKEN" VARCHAR2(30), 
	"MANDATORY" VARCHAR2(1) DEFAULT 'N'
   )
