--------------------------------------------------------
--  DDL for Table XXPM_PROPERTY_CONTACTS_BKP_7_OCT19
--------------------------------------------------------

  CREATE TABLE "XXPM_PROPERTY_CONTACTS_BKP_7_OCT19" 
   (	"CONTACT_ID" NUMBER, 
	"PROPERTY_ID" NUMBER, 
	"BUILD_ID" NUMBER, 
	"UNIT_ID" NUMBER, 
	"CONTACT_TYPE" VARCHAR2(60), 
	"VEND_ID" NUMBER, 
	"VEND_SITE_ID" NUMBER, 
	"CONTACT_NUMBER" VARCHAR2(60), 
	"ACTIVE_YN" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"EMP_ID" NUMBER
   )
