--------------------------------------------------------
--  DDL for Table XXPM_ORG_ASSIGNMENT
--------------------------------------------------------

  CREATE TABLE "XXPM_ORG_ASSIGNMENT" 
   (	"ORG_ASSIGN_ID" NUMBER, 
	"PROPERTY_ID" NUMBER, 
	"BUILD_ID" NUMBER, 
	"UNIT_ID" NUMBER, 
	"ORG_ID" NUMBER, 
	"SALABLE" VARCHAR2(1), 
	"LEASEABLE" VARCHAR2(1), 
	"SUB_LEASEABLE" VARCHAR2(1), 
	"COMMISION_ONLY_LEASE" VARCHAR2(1), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"ACTIVE_YN" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
