--------------------------------------------------------
--  DDL for Package Body XXPM_PCS_APPROVAL_PKG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "XXPM_PCS_APPROVAL_PKG" 
IS
PROCEDURE GET_MILESTONE_DATA(P_MS_ID VARCHAR2)
IS
  l_cursor sys_refcursor;
BEGIN
  OPEN l_cursor FOR 
  SELECT S_NO , MS_HDR_ID , PAYMENT_PLAN , PAYMENT_PLAN_SHORT_CODE , REVISION_NO , 
  REVISED_BY , REVISION_DATE , BUSINESS_UNIT , 
  START_DATE , END_DATE , PAYMENT_PLAN_DATE , 
  DESCRIPTION , INSTALLMENT_TYPE , INSTALLMENT_PERCENTAGE , 
  CHARGE_TYPE , PAYMENT_TERM , INSTALLMENT_METHOD , INSTALLMENT_EVENT , 
  PROJ_MS_ID , PROJECT_START_DATE , PROJECT_END_DATE , 
  PERIOD_OCCURANCE , PERIOD_DURATION , PERIOD_VALUES , DUE_DAYS , DUE_DATE , REMARKS 
   FROM XXPM_MILESTONE_PCS_V WHERE MS_HDR_ID =P_MS_ID;


  APEX_JSON.open_object;
  APEX_JSON.write('GetVal', l_cursor);
  APEX_JSON.close_object;

END GET_MILESTONE_DATA;
END XXPM_PCS_APPROVAL_PKG;
