--------------------------------------------------------
--  DDL for Table XXPM_QUALIFIERS
--------------------------------------------------------

  CREATE TABLE "XXPM_QUALIFIERS" 
   (	"QLFY_ID" NUMBER, 
	"QUALIFIERS" VARCHAR2(60), 
	"OPERATOR" VARCHAR2(60), 
	"QUALIFIER_FROM" VARCHAR2(240), 
	"QUALIFIER_TO" VARCHAR2(240), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"ACTIVE_YN" VARCHAR2(1), 
	"REVISION_NO" NUMBER, 
	"REVISION_DATE" DATE, 
	"REVISED_BY" VARCHAR2(60), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
