--------------------------------------------------------
--  DDL for Table XXPM_MODIFIERS
--------------------------------------------------------

  CREATE TABLE "XXPM_MODIFIERS" 
   (	"MOD_ID" NUMBER, 
	"MOD_NAME" VARCHAR2(60), 
	"MOD_NAME_TL" VARCHAR2(60), 
	"MOD_LEVEL" VARCHAR2(60), 
	"MOD_CATEGORY" VARCHAR2(60), 
	"CHARGE_TYPE" VARCHAR2(60), 
	"MOD_TYPE" VARCHAR2(60), 
	"MOD_VALUE" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"ACTIVE_YN" VARCHAR2(1), 
	"REVISION_NO" NUMBER, 
	"REVISION_DATE" DATE, 
	"REVISED_BY" VARCHAR2(60), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
