--------------------------------------------------------
--  DDL for View XXPM_APPROVAL_HIS_V
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "XXPM_APPROVAL_HIS_V" ("APPR_HIST_ID", "FUNC_ID", "FUNC_REF_ID", "SEQ_NUMBER", "APPR_ROLE", "APPROVER_ID", "USER_NAME", "USER_NAME_DISP", "USER_EMAIL_ID", "FLOW_LEVEL", "USER_GRP_ID", "CYCLE_NO", "CYCLE_FLAG", "SUBMISSION_DATE", "ACTION_DATE", "DESCRIPTION", "STATUS", "CREATED_BY", "CREATION_DATE", "LAST_UPDATED_BY", "LAST_UPDATE_DATE", "LAST_UPDATE_LOGIN") AS 
  select
HIS.APPR_HIST_ID,
HIS.FUNC_ID,
HIS.FUNC_REF_ID,
HIS.SEQ_NUMBER,
HIS.APPR_ROLE,
HIS.APPROVER_ID,
USE.USER_NAME,
USE.USER_NAME_DISP,
USE.USER_EMAIL_ID,
HIS.FLOW_LEVEL,              
HIS.USER_GRP_ID,             
HIS.CYCLE_NO,                
HIS.CYCLE_FLAG,              
HIS.SUBMISSION_DATE,
HIS.ACTION_DATE,
HIS.DESCRIPTION,
HIS.STATUS,
HIS.CREATED_BY,              
HIS.CREATION_DATE,           
HIS.LAST_UPDATED_BY,         
HIS.LAST_UPDATE_DATE,        
HIS.LAST_UPDATE_LOGIN       
from XXFND_FUNC_APPROVAL_HIST HIS, XXFND_USER USE
WHERE HIS.APPROVER_ID=USE.USER_ID
ORDER BY 1 ASC
