--------------------------------------------------------
--  DDL for Sequence XXPM_PROPERTY_MORTGAGE_ID_S
--------------------------------------------------------

   CREATE SEQUENCE  "XXPM_PROPERTY_MORTGAGE_ID_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 108 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
