--------------------------------------------------------
--  DDL for Table XXPM_PROPERTY_CARPARKS_BKP_7_OCT19
--------------------------------------------------------

  CREATE TABLE "XXPM_PROPERTY_CARPARKS_BKP_7_OCT19" 
   (	"CARPARK_ID" NUMBER, 
	"UNIT_ID" NUMBER, 
	"CP_UNIT_ID" NUMBER, 
	"ALLOT_TYPE" VARCHAR2(30), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
