--------------------------------------------------------
--  DDL for Table XXPM_RECEIPT_APP_ACC_REPORT
--------------------------------------------------------

  CREATE TABLE "XXPM_RECEIPT_APP_ACC_REPORT" 
   (	"CASH_RECEIPT_ID" NUMBER, 
	"RECEIPT_NUMBER" VARCHAR2(240), 
	"RECEIPT_DATE" TIMESTAMP (6), 
	"DEPOSIT_DATE" TIMESTAMP (6), 
	"GL_DATE" TIMESTAMP (6), 
	"CUSTOMER_TRX_ID" NUMBER, 
	"TRX_NUMBER" VARCHAR2(240), 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_ON" TIMESTAMP (6), 
	"RECEIVABLE_APPLICATION_ID" NUMBER
   )
