--------------------------------------------------------
--  DDL for Table XXPM_INVOICE_NUMBER
--------------------------------------------------------

  CREATE TABLE "XXPM_INVOICE_NUMBER" 
   (	"PROJ_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(240), 
	"PROJECT_NUMBER" VARCHAR2(25), 
	"ORG_ID" NUMBER, 
	"START_DATE" DATE, 
	"COMPLETION_DATE" DATE, 
	"CLOSED_DATE" DATE, 
	"COST_CENTER_CODE" VARCHAR2(60), 
	"ORIG_SYSTEM_REF" NUMBER, 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"INV_PREFIX" VARCHAR2(10), 
	"SEQ_NO" NUMBER
   )
