--------------------------------------------------------
--  DDL for Table XXREP_PROJECT_SUMMARY
--------------------------------------------------------

  CREATE TABLE "XXREP_PROJECT_SUMMARY" 
   (	"BATCH_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"PROJECT_NUM" VARCHAR2(25), 
	"PROJECT_NAME" VARCHAR2(240), 
	"PROJECT_STATUS" VARCHAR2(80), 
	"BU_ID" NUMBER, 
	"BUDGET_VALUE_O" NUMBER, 
	"BUDGET_VALUE_C" NUMBER, 
	"BUDGET_VALUE_P" NUMBER, 
	"CONTRACT_VALUE" NUMBER, 
	"PVO_APPROVED" NUMBER, 
	"PVO_SUBMITTED" NUMBER, 
	"VO" NUMBER, 
	"LAND_AREA" NUMBER, 
	"FLOOR_AREA" NUMBER, 
	"SALEABLE_AREA" NUMBER, 
	"BUILD_AREA" NUMBER, 
	"PC_AMOUNT" NUMBER, 
	"PC_PAID" NUMBER, 
	"REVENUE_VALUE" NUMBER
   )
