--------------------------------------------------------
--  DDL for Table XXREP_PROJECT_BUDGET
--------------------------------------------------------

  CREATE TABLE "XXREP_PROJECT_BUDGET" 
   (	"PROJECT_ID" NUMBER, 
	"TASK_ID" NUMBER, 
	"BUDGET_VALUE_O" NUMBER, 
	"BUDGET_VALUE_C" NUMBER, 
	"BUDGET_VALUE_P" NUMBER, 
	"PVO_APPROVED_LM" NUMBER, 
	"PVO_SUBMITTED_LM" NUMBER, 
	"PVO_APPROVED" NUMBER, 
	"PVO_SUBMITTED" NUMBER, 
	"PC_PAID" NUMBER, 
	"VENDOR_NAME" VARCHAR2(255), 
	"CONTRACT_VALUE_O" NUMBER, 
	"VO_LM" NUMBER, 
	"VO" NUMBER
   )
