--------------------------------------------------------
--  DDL for Table XXSTG_POSITIONS
--------------------------------------------------------

  CREATE TABLE "XXSTG_POSITIONS" 
   (	"POSITION_ID" NUMBER, 
	"POSITION_NAME" VARCHAR2(240), 
	"POSITION_CODE" VARCHAR2(60), 
	"JOB_ID" NUMBER, 
	"JOB_NAME" VARCHAR2(240), 
	"JOB_CODE" VARCHAR2(60), 
	"PERSON_ID" NUMBER, 
	"PERSON_NUMBER" VARCHAR2(30), 
	"FULL_NAME" VARCHAR2(240), 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
