--------------------------------------------------------
--  DDL for Table XXSTG_MOVE_IN_OUT
--------------------------------------------------------

  CREATE TABLE "XXSTG_MOVE_IN_OUT" 
   (	"S_NO" NUMBER, 
	"MOVE_IN_OUT_ID" NUMBER, 
	"FUNC_ID" NUMBER, 
	"LEASE_AGREEMENT_ID" NUMBER, 
	"BOOKING_ID" NUMBER, 
	"BOOKING_NUMBER" VARCHAR2(60), 
	"LEASE_NUMBER" VARCHAR2(60), 
	"MOVE_IN_OUT_NUMBER" VARCHAR2(60), 
	"MOVE_IN_OUT_DATE" DATE, 
	"CUSTOMER" VARCHAR2(250), 
	"RESOURCE_NAME" VARCHAR2(60), 
	"IN_OUT_FLAG" VARCHAR2(1), 
	"MOVE_STATUS" VARCHAR2(60), 
	"MOVE_STATUS_CODE" VARCHAR2(60), 
	"DESCRIPTION" VARCHAR2(240), 
	"ORG_ID" NUMBER, 
	"PROPERTY_ID" NUMBER, 
	"BUILDING_ID" NUMBER, 
	"STATUS" VARCHAR2(30), 
	"ERROR_MSG" VARCHAR2(2000)
   )
