--------------------------------------------------------
--  DDL for Table XXSTG_VEND_SITES
--------------------------------------------------------

  CREATE TABLE "XXSTG_VEND_SITES" 
   (	"VEND_SITE_ID" NUMBER, 
	"VEND_ID" NUMBER, 
	"SITE_NUMBER" VARCHAR2(30), 
	"ADDRESS1" VARCHAR2(240), 
	"ADDRESS2" VARCHAR2(240), 
	"ADDRESS3" VARCHAR2(240), 
	"ADDRESS4" VARCHAR2(240), 
	"CITY" VARCHAR2(60), 
	"POSTAL_CODE" VARCHAR2(60), 
	"STATE" VARCHAR2(60), 
	"PROVINCE" VARCHAR2(60), 
	"COUNTY" VARCHAR2(60), 
	"COUNTRY" VARCHAR2(60), 
	"ORG_ID" NUMBER, 
	"ORIG_SYSTEM_REF" NUMBER, 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
