--------------------------------------------------------
--  DDL for Table XXSTG_RECEIPT_METHOD
--------------------------------------------------------

  CREATE TABLE "XXSTG_RECEIPT_METHOD" 
   (	"RECEIPT_METHOD_ID" NUMBER, 
	"RECEIPT_METHOD_NAME" VARCHAR2(30), 
	"ORG_ID" NUMBER, 
	"TYPE" VARCHAR2(30), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"REMIT_BANK_ACCT_USE_ID" NUMBER, 
	"BANK_ACCOUNT_NUM" VARCHAR2(60), 
	"BANK_NAME" VARCHAR2(240), 
	"BANK_BRANCH_NAME" VARCHAR2(240), 
	"REC_BANK_ACC_NUM" VARCHAR2(60), 
	"REC_BANK_NAME" VARCHAR2(240), 
	"REC_BANK_BRANCH_NAME" VARCHAR2(240)
   )
