--------------------------------------------------------
--  DDL for Table XXSTG_SALESPERSON
--------------------------------------------------------

  CREATE TABLE "XXSTG_SALESPERSON" 
   (	"SP_ID" NUMBER, 
	"SP_NAME" VARCHAR2(240), 
	"SP_NAME_TL" VARCHAR2(240), 
	"SP_NUMBER" VARCHAR2(30), 
	"EMAIL_ID" VARCHAR2(60), 
	"CONTACT_NUMBER" VARCHAR2(60), 
	"ORIG_SYSTEM_REF" NUMBER, 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
