--------------------------------------------------------
--  DDL for Table XXSTG_ORGANIZATIONS_BKP
--------------------------------------------------------

  CREATE TABLE "XXSTG_ORGANIZATIONS_BKP" 
   (	"ORG_ID" NUMBER, 
	"ORG_NAME" VARCHAR2(240), 
	"ORG_NAME_TL" VARCHAR2(240), 
	"SHORT_CODE" VARCHAR2(150), 
	"LEGAL_ENTITY_ID" NUMBER, 
	"LEDGER_ID" NUMBER, 
	"LEDGER_NAME" VARCHAR2(100), 
	"LEDGER_GL_CODE" VARCHAR2(20), 
	"ORG_GL_CODE" VARCHAR2(20), 
	"ORIG_SYSTEM_REF" NUMBER, 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
