--------------------------------------------------------
--  DDL for Table XXTEST_PROPERTY_UNITS_TEMP2
--------------------------------------------------------

  CREATE TABLE "XXTEST_PROPERTY_UNITS_TEMP2" 
   (	"PROPERTY_ID" NUMBER, 
	"BUILD_NAME" VARCHAR2(240), 
	"BUILD_ID" NUMBER, 
	"UNIT_NAME" VARCHAR2(240), 
	"UNIT_NUMBER" VARCHAR2(240), 
	"UNIT_SHORTCODE" VARCHAR2(240), 
	"PARENT_UNIT_ID" NUMBER, 
	"DOC_REF_NUMBER_1" VARCHAR2(240), 
	"DOC_REF_NUMBER_2" VARCHAR2(240), 
	"DOC_REF_NUMBER_3" VARCHAR2(240), 
	"FLOOR_NUMBER" VARCHAR2(240), 
	"NO_OF_ROOMS" NUMBER, 
	"UNIT_TYPE" VARCHAR2(240), 
	"AREA_TYPE" VARCHAR2(240), 
	"VIEW_TYPE" VARCHAR2(240), 
	"CHARGEABLE_AREA" VARCHAR2(240), 
	"UOM" VARCHAR2(240), 
	"UNIT_CATEGORY" VARCHAR2(240), 
	"STATUS" VARCHAR2(240), 
	"SALEABLE_YN" VARCHAR2(240), 
	"LEASEABLE_YN" VARCHAR2(240), 
	"SALE_AVAILABLE_YN" VARCHAR2(240), 
	"LEASE_AVAILABLE_YN" VARCHAR2(240), 
	"FREE_HOLD_YN" VARCHAR2(240), 
	"LEASE_HOLD_YN" VARCHAR2(240), 
	"LIST_FOR_BROKERS" VARCHAR2(240), 
	"LIST_FOR_INTERNAL" VARCHAR2(240)
   )
