create or replace TRIGGER ACTIVITY_CANCELLATION_test
AFTER INSERT ON XXPM_CANCELLATION 
FOR EACH ROW  
DECLARE
BEGIN

XXPM_ACTIVITY_PKG_TEST.XXPM_PROC_ACTIVITY(:NEW.FUNC_ID, :NEW.CANCEL_ID,
        :NEW.ORG_ID, :NEW.BOOKING_ID, 'CNSB',:NEW.CANCEL_NUMBER,:NEW.CREATED_BY);

--  SELECT PROPERTY_ID INTO P_PROPERTY_ID FROM XXPM_BOOKING_DETAIL WHERE BOOKING_HDR_ID = :NEW.BOOKING_ID;
--  SELECT BUILDING_ID INTO P_BUILD_ID FROM XXPM_BOOKING_DETAIL WHERE BOOKING_HDR_ID = :NEW.BOOKING_ID;
--  SELECT UNIT_ID INTO P_UNIT_ID FROM XXPM_BOOKING_DETAIL WHERE BOOKING_HDR_ID = :NEW.BOOKING_ID;
--    INSERT
--    INTO XXPM_ACTIVITY_LOG
--      (
--        ACTIVITY_ID,
--        ACTIVITY_NUMBER,
--        ACTIVITY_DATE,
--        FUNC_ID,
--        SOURCE_FUNC_ID,
--        SOURCE_FUNC_REF_ID,
--        ORG_ID,
--        PROPERTY_ID,
--        BUILD_ID,
--        UNIT_ID,
--        ACTIVITY_TYPE,
--        DESCRIPTION,
--        CREATED_BY,
--        CREATION_DATE,
--        LAST_UPDATED_BY,
--        LAST_UPDATE_DATE,
--        LAST_UPDATE_LOGIN
--      )
--      VALUES
--      (
--        XXPM_ACTIVITY_ID_S.nextval,
--        'AL-'|| XXPM_ACTIVITY_ID_S.nextval,
--        sysdate,
--        49,
--        :NEW.FUNC_ID,
--        :NEW.CANCEL_ID,
--        :NEW.ORG_ID,
--        P_PROPERTY_ID,
--        P_BUILD_ID,
--        P_UNIT_ID,
--        'BKSB',
--        :NEW.CANCEL_NUMBER,
--        :NEW.CREATED_BY,
--        SYSDATE,
--        :NEW.CREATED_BY,
--        SYSDATE,
--        :NEW.CREATED_BY
--      );


END ACTIVITY_CANCELLATION_test;