--------------------------------------------------------
--  DDL for Table XXDMPL_OWNER_DTLE
--------------------------------------------------------

  CREATE TABLE "XXDMPL_OWNER_DTLE" 
   (	"OWNER_ID" VARCHAR2(60), 
	"PROPERTY_NUMBER" VARCHAR2(60), 
	"BUILD_NUMBER" VARCHAR2(60), 
	"UNIT_NUMBER" VARCHAR2(60), 
	"VEND_ID" VARCHAR2(60), 
	"VEND_SITE_ID" VARCHAR2(60), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"BATCH_ID" NUMBER, 
	"INTERFACE_STATUS_FLAG" VARCHAR2(1), 
	"INTERFACE_ID" NUMBER, 
	"ERR_MSG" VARCHAR2(2000), 
	"ERR_DESCRIPTION" VARCHAR2(2000), 
	"VALIDATED_BY" VARCHAR2(60), 
	"VALIDATED_DATE" TIMESTAMP (6), 
	"PROCESSED_BY" VARCHAR2(60), 
	"PROCESSED_DATE" TIMESTAMP (6), 
	"PRIMARY_YN" VARCHAR2(1), 
	"DESCRIPTION" VARCHAR2(4000)
   )
