--------------------------------------------------------
--  DDL for Table XXSTG_LOCATIONS
--------------------------------------------------------

  CREATE TABLE "XXSTG_LOCATIONS" 
   (	"LOC_ID" NUMBER, 
	"LOCATION_NAME" VARCHAR2(240), 
	"LOCATION_NAME_TL" VARCHAR2(240), 
	"COUNTRY" VARCHAR2(60), 
	"COUNTRY_TL" VARCHAR2(60), 
	"ADDRESS1" VARCHAR2(240), 
	"ADDRESS1_TL" VARCHAR2(240), 
	"ADDRESS2" VARCHAR2(240), 
	"ADDRESS2_TL" VARCHAR2(240), 
	"ADDRESS3" VARCHAR2(240), 
	"ADDRESS3_TL" VARCHAR2(240), 
	"ADDRESS4" VARCHAR2(240), 
	"ADDRESS4_TL" VARCHAR2(240), 
	"CITY" VARCHAR2(60), 
	"CITY_TL" VARCHAR2(60), 
	"POSTAL_CODE" VARCHAR2(60), 
	"POSTAL_CODE_TL" VARCHAR2(60), 
	"STATE" VARCHAR2(60), 
	"STATE_TL" VARCHAR2(60), 
	"PROVINCE" VARCHAR2(60), 
	"PROVINCE_TL" VARCHAR2(60), 
	"COUNTY" VARCHAR2(60), 
	"COUNTY_TL" VARCHAR2(60), 
	"ORIG_SYSTEM_REF" NUMBER, 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"ORG_ID" NUMBER, 
	"LICENSE_NO" VARCHAR2(60), 
	"PO_BOX" VARCHAR2(60)
   )
