--------------------------------------------------------
--  DDL for Type PL_MODIFIERS_OBJ_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "PL_MODIFIERS_OBJ_TYPE" force AS OBJECT (	
PL_MOD_ID	NUMBER,
PL_NUMBER	VARCHAR2(60 BYTE),
MOD_ID	NUMBER,
START_DATE	VARCHAR2(200),
END_DATE	VARCHAR2(200),
ACTIVE_YN	VARCHAR2(1 BYTE),
PL_MOD_NUMBER VARCHAR2(50),
CONSTRUCTOR FUNCTION PL_MODIFIERS_OBJ_TYPE RETURN SELF AS RESULT);
