--------------------------------------------------------
--  DDL for Table XXFND_CHECKLIST_RESPONSE
--------------------------------------------------------

  CREATE TABLE "XXFND_CHECKLIST_RESPONSE" 
   (	"CL_RES_ID" NUMBER, 
	"FUNC_ID" NUMBER, 
	"FUNC_REF_ID" NUMBER, 
	"FUNC_CL_ID" NUMBER, 
	"ITEM_RESPONSE1" VARCHAR2(4000), 
	"ITEM_RESPONSE2" BLOB, 
	"RESPONDED_YN" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
