--------------------------------------------------------
--  DDL for Table XXFND_FUNC_APPR_LEVELS
--------------------------------------------------------

  CREATE TABLE "XXFND_FUNC_APPR_LEVELS" 
   (	"APPR_LEVEL_ID" NUMBER, 
	"FUNC_ID" NUMBER, 
	"LEVEL_NO" NUMBER, 
	"LEVEL_NAME" VARCHAR2(60), 
	"LEVEL_TYPE" VARCHAR2(1), 
	"APPR_BY_ALL" VARCHAR2(1), 
	"ACTIVE_YN" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
