--------------------------------------------------------
--  DDL for Table XXPM_PROPERTY_ESCROW_BKP_7_OCT19
--------------------------------------------------------

  CREATE TABLE "XXPM_PROPERTY_ESCROW_BKP_7_OCT19" 
   (	"ESCROW_ID" NUMBER, 
	"PROPERTY_ID" NUMBER, 
	"BANK_ACNT_ID" NUMBER, 
	"ACTIVE_YN" VARCHAR2(1), 
	"INACTIVE_ON" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150), 
	"BUILD_ID" NUMBER, 
	"FAVOURING" VARCHAR2(240), 
	"REMARKS" VARCHAR2(2000)
   )
