--------------------------------------------------------
--  File created - Monday-October-26-2020   
--------------------------------------------------------
@C:\Users\Balaji\Documents\sale_backup\AA_UNIT.sql
@C:\Users\Balaji\Documents\sale_backup\AGENT_DL.sql
@C:\Users\Balaji\Documents\sale_backup\COMPANY_LOGO.sql
@C:\Users\Balaji\Documents\sale_backup\DUMMY_UNIT_STATUS.sql
@C:\Users\Balaji\Documents\sale_backup\PLAN_TABLE.sql
@C:\Users\Balaji\Documents\sale_backup\PS_TXN.sql
@C:\Users\Balaji\Documents\sale_backup\XXDMPL_OWNER_DTLE.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_BOOKING_CUSTOMER.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_BOOKING_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_BOOKING_HEADER.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_EXCEL_STG_MAPPING.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_INTERFACE.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_INTERFACE_MASTER.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_INVOICE_HEADER.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_INVOICE_LINES.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_MILESTONE_DTL.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_MILESTONE_HDR.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_OFFER_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_OFFER_HEADER.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_OFFER_MILESTONE_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PL_HEADER.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PL_LINES.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PL_MODIFIERS.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PL_QUALIFIERS.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PROPERTY_AREA.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PROPERTY_CARPARKS.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PROPERTY_CARPARKS_BCK0309.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PROPERTY_FEATURES.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PROPERTY_FIX_FITTINGS.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_PROPERTY_UNITS.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_RECEIPT.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_RECEIPT_DETAILS.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALES_BOOKINGS.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALES_INVOICES.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALES_MILESTONES.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALES_RECEIPTS.sql
@C:\Users\Balaji\Documents\sale_backup\XXDM_SALES_RECEIPTS_BKP.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_ATTRIBUTES.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_ATTR_COMB.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_ATTR_GROUP.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_ROLES.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_USERS.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_USER_GROUP.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_APPR_USER_LEVELS.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_CHECKLIST_RESPONSE.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_CURRENCIES.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_DATA_COMBINATION.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_DATA_GROUP.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_DATA_GROUP_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_DATA_SECURITY.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEXS.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEXS_CATEGORY.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEXS_DATA.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FLEXS_FIELDS.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNCTIONS.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_APPROVALS.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_APPROVAL_HIST.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_APPR_LEVELS.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_ATTACHMENT.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_FUNC_CHECKLIST.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_LOOKUP_TYPES.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_LOOKUP_VALUES.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_MAIN_MENU.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_MENU_ACCESS.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_REPORT_PARAMS.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SCHEDULE_ERR_LOG_T.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SCHEDULE_LIST_T.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SCHEDULE_T.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SETUP_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_SUB_MENU.sql
@C:\Users\Balaji\Documents\sale_backup\XXFND_USER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPL_OWNER_DTLE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_ACTIVITY_LOG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_APPLY_CREDIT_MEMO.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CHANGE_DLT.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AREA_CHANGE_HDR.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_AR_SETUP.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BILLING.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCK_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BLOCK_HEADER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUSTOMER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUSTOMER_DTL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_CUSTOMER_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_DETAIL_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_EVENTS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_EVENTS_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HEADER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HEADER_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_HEADER_REV.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_BCK0109.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_BCK3008.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_BCK31082.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_BCK_3108.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_BKP_13_DEC.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_REV.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_SEPT_11.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOKING_MILESTONES_SEPT_12.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOK_MS_REV_DTL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_BOOK_MS_REV_HDR.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CANCELLATION.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CANCEL_NOTIFY.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_CUST_DETAIL_TYPES.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_EXTEN_CANCEL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_HDR_SYNC.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_HEADER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_HEADER_BAYSWATER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_HEADER_BCK0109.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_HEADER_BCK0809.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_HEADER_SEPT_POSTLIVE_11.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_HEADER_SEPT_RECON_11.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_LINES.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_LINES_BCK_3108.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_LINES_DATA_FIX.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_LINES_SEPT_POSTLIVE_11.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_LINES_SEPT_RECON_11.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_INVOICE_NUMBER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_KEY_DETAILS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_LEAD.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_LEASE_AGREEMENT.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_DTL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_DTL_BCK3008.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_DTL_BKP31.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_DTL_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_DTL_PROJECTS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_DTL_TMP1.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_HDR.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MILESTONE_HDR_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MODIFIERS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IN_OUT.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IO_CUST_VISIT.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IO_FIXTURES.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IO_KEYS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_MOVE_IO_METERS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_DETAIL_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_HEADER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_HEADER_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_MILESTONE_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_OFFER_MILESTONE_DETAIL_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_ORG_ASSIGNMENT.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_DISCOUNTS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_HEADER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_HEADER_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_LINES.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_LINES_BKP_DEC6.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_LINES_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_MODIFIERS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_MODIFIERS_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_QUALIFIERS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PL_QUALIFIERS_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_AREA.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_AREA_BKP.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_AREA_BKP_7_OCT19.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_BUILDINGS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_BUILDINGS_BKP_7_OCT19.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_CARPARKS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_CARPARKS_BCK0309.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_CARPARKS_BKP_7_OCT19.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_CONTACTS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_CONTACTS_BKP_7_OCT19.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_ESCROW.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_ESCROW_BKP_7_OCT19.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_FEATURES.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_FIX_FITTINGS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_FIX_FITTINGS_BKP_7_OCT19.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MASTER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MASTER_BKP_7_OCT19.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MILESTONE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MILESTONE_BKP_7_OCT19.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MORTGAGE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_MORTGAGE_BKP_7_OCT19.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_ORG.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_RESERVATION.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_UNITS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_PROPERTY_UNITS_BKP_7_OCT19.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_QUALIFIERS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPTS_BACKUP_28.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPTS_DETAILS_BACKUP_28.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_0209.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_29_AUG_BKP.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_APP_ACC_REPORT.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_BACKUP.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_BKP21_OCT.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_DETAILS.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_DETAILS_0209.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_DETAILS_29_AUG_BKP.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_DETAIL_BACKUP.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_HDR_ACC_REPORT.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECEIPT_UPDATE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECOMMEND_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECOMMEND_HEADER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECOMMEND_HEADER_H.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_RECOMMEND_OTHER_CHARGES.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_REGISTRATION.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_REVISION.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_REVISION_LINE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_SALES_RECEIPTS_TSQ2.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_SETUP_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_TMP2_BOOKIMG_MILESTONE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_TMP_BOOKIMG_MILESTONE.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNBLOCK_DETAIL.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNBLOCK_HEADER.sql
@C:\Users\Balaji\Documents\sale_backup\XXPM_UNIT_TRANSFER_DETAILS.sql
@C:\Users\Balaji\Documents\sale_backup\XXREP_PROJECT.sql
@C:\Users\Balaji\Documents\sale_backup\XXREP_PROJECT_BUDGET.sql
@C:\Users\Balaji\Documents\sale_backup\XXREP_PROJECT_SUMMARY.sql
@C:\Users\Balaji\Documents\sale_backup\XXREP_TASK.sql
@C:\Users\Balaji\Documents\sale_backup\XXSF_AGENCY.sql
@C:\Users\Balaji\Documents\sale_backup\XXSF_AGENTS.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_AR_TXN_SOURCE.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_AR_TXN_TYPE.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_BANKS.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_BANK_ACCOUNTS.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_CUSTOMER.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_CUST_CONTACTS.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_CUST_SITES.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_EMPLOYEE.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_GL_CODE_COMBINATION.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_LEAD.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_LEASE_AGREEMENT_HDR.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_LEASE_MS_DTL.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_LOCATIONS.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_MOVE_IN_OUT.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_ORGANIZATIONS.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_ORGANIZATIONS_BKP.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_PAY_TERMS.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_POSITIONS.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_PROJECTS.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_PROJECT_MILESTONES.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_PROJECT_MILESTONES_BKP.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_RECEIPT.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_RECEIPT_METHOD.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_RECEIPT_OLD.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_SALESPERSON.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_VENDOR.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_VEND_CONTACTS.sql
@C:\Users\Balaji\Documents\sale_backup\XXSTG_VEND_SITES.sql
@C:\Users\Balaji\Documents\sale_backup\XXTEMP_INV_DATA_FIX1.sql
@C:\Users\Balaji\Documents\sale_backup\XXTEMP_INV_DATA_FIX2.sql
@C:\Users\Balaji\Documents\sale_backup\XXTEST_PROPERTY_AREA_TEMP2.sql
@C:\Users\Balaji\Documents\sale_backup\XXTEST_PROPERTY_UNITS_TEMP2.sql
