--------------------------------------------------------
--  DDL for View XXPM_PAYMENT_CHANGE_MS_PCS_V
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "XXPM_PAYMENT_CHANGE_MS_PCS_V" ("MS_REV_DTL_ID", "MILESTONE_TYPE", "INSTALLMENT_PCT", "INSTALLMENT_METHOD", "INSTALLMENT_EVENT", "SEQ_NUMBER", "INSTALLMENT_AMOUNT", "INSTALLMENT_PCT_R", "INSTALLMENT_AMOUNT_R", "CHARGE_TYPE", "CHARGE_TYPE_DISP", "INSTALLMENT_TYPE_DISP", "INSTALLMENT_TYPE", "PAYMENT_TERM", "PAYMENT_TERM_DISP", "DUE_DAYS", "DUE_DATE", "INVOICE_ID", "INVOICE_NUMBER", "MS_REV_ID") AS 
  SELECT DISTINCT xbmrd.MS_REV_DTL_ID,
    xbmrd.MILESTONE_TYPE ,
    xbmrd.INSTALLMENT_PCT ,
    xbmrd.INSTALLMENT_METHOD ,
    xbmrd.INSTALLMENT_EVENT ,
    xbmrd.SEQ_NUMBER,
    xbmrd.INSTALLMENT_AMOUNT,
    xbmrd.INSTALLMENT_PCT_R ,
    xbmrd.INSTALLMENT_AMOUNT_R,
    xbmrd.CHARGE_TYPE,
    LKV1.LOOKUP_VALUE_NAME_DISP AS CHARGE_TYPE_DISP,
    LKV.LOOKUP_VALUE_NAME_DISP INSTALLMENT_TYPE_DISP,
    xbmrd.INSTALLMENT_TYPE,
    xbmrd.PAYMENT_TERM ,
    PAY.TERM_NAME AS PAYMENT_TERM_DISP ,
    xbmrd.DUE_DAYS ,
    TRUNC(xbmrd.DUE_DATE) ,
    xbmrd.INVOICE_ID,
    XIH.INVOICE_NUMBER,
    xbmrd.MS_REV_ID --added on 23-May
  FROM XXPM_BOOK_MS_REV_DTL xbmrd ,
    XXPM_INVOICE_HEADER xih ,
    XXFND_LOOKUP_V LKV ,
    XXFND_LOOKUP_V LKV1 ,
    XXSTG_PAY_TERMS PAY
  WHERE xih.INVOICE_ID(+)   =xbmrd.INVOICE_ID
  AND xbmrd.INSTALLMENT_TYPE=LKV.LOOKUP_VALUE_NAME(+)
    --and LKV.LOOKUP_TYPE_NAME='MILESTONE_INSTALLMENT'
  AND xbmrd.CHARGE_TYPE    =LKV1.LOOKUP_VALUE_NAME(+)
  AND LKV1.LOOKUP_TYPE_NAME='CHARGE_TYPE'
  AND xbmrd.PAYMENT_TERM   =PAY.TERM_ID(+)
