--------------------------------------------------------
--  DDL for Table XXFND_APPR_ATTRIBUTES
--------------------------------------------------------

  CREATE TABLE "XXFND_APPR_ATTRIBUTES" 
   (	"ATTR_ID" NUMBER, 
	"ATTR_GRP_ID" NUMBER, 
	"SEQ_NUMBER" NUMBER, 
	"ATTRIBUTE_COLUMN" VARCHAR2(10), 
	"COLUMN_NAME" VARCHAR2(30), 
	"SRC_TABLE" VARCHAR2(60), 
	"SRC_COLUMN" VARCHAR2(60), 
	"SRC_DISP_COLUMN" VARCHAR2(60), 
	"SRC_LOOKUP_TYPE" VARCHAR2(60), 
	"ACTIVE_YN" VARCHAR2(1), 
	"CREATED_BY" VARCHAR2(60), 
	"CREATION_DATE" TIMESTAMP (6), 
	"LAST_UPDATED_BY" VARCHAR2(60), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"LAST_UPDATE_LOGIN" VARCHAR2(150)
   )
